// Code generated by sdkgen product; DO NOT EDIT.
package sts

import (
	"context"
	"encoding/json/v2"
	"errors"
	alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"
	"github.com/rambow-cloud/alicloud-go-sdk-x/internal/rpcmodel"
)

// Options configures this service. Configured extension objects remain shared.
type Options alicloud.Config

// Client is immutable and concurrency safe. Construct with NewFromConfig.
type Client struct{ runtime *alicloud.Client }

// NewFromConfig copies configuration and middleware registrations and applies options.
// Nil options and invalid configuration fail; callbacks must not retain Options.
func NewFromConfig(config alicloud.Config, optFns ...func(*Options)) (*Client, error) {
	options := Options(config)
	options.Middleware = append(options.Middleware[:0:0], options.Middleware...)
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil service option")
		}
		f(&options)
	}
	runtime, err := alicloud.NewClient(alicloud.Config(options))
	if err != nil {
		return nil, err
	}
	return &Client{runtime: runtime}, nil
}

// New constructs a service client with the same behavior as NewFromConfig.
func New(config alicloud.Config, optFns ...func(*Options)) (*Client, error) {
	return NewFromConfig(config, optFns...)
}

// Options returns a configuration snapshot; extension objects remain shared.
func (c *Client) Options() Options { return Options(c.runtime.Config()) }
func (c *Client) callOptions(region string, optFns []func(*Options)) ([]func(*alicloud.CallOptions), error) {
	if len(optFns) == 0 {
		return nil, nil
	}
	options := c.Options()
	if region != "" {
		options.Region = region
	}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil operation option")
		}
		f(&options)
	}
	config := alicloud.Config(options)
	return []func(*alicloud.CallOptions){func(o *alicloud.CallOptions) { o.Config = &config; o.Region = config.Region }}, nil
}
func invoke[I, O any](ctx context.Context, c *Client, input *I, op alicloud.Operation, method string, hasRegion bool, prepare func(context.Context, *I) error, validate func(*I) error, optFns []func(*Options)) (*O, alicloud.Metadata, error) {
	fail := func(err error) (*O, alicloud.Metadata, error) {
		if ctx.Err() != nil {
			err = ctx.Err()
		}
		return nil, alicloud.Metadata{}, &alicloud.OperationError{Service: op.Service, Operation: op.Name, Err: err}
	}
	if err := ctx.Err(); err != nil {
		return fail(err)
	}
	if c == nil || c.runtime == nil {
		return fail(errors.New("uninitialized service client"))
	}
	in, err := rpcmodel.Snapshot(ctx, input)
	if err != nil {
		return fail(err)
	}
	if prepare != nil {
		if err := prepare(ctx, in); err != nil {
			return fail(err)
		}
	}
	if validate != nil {
		if err := validate(in); err != nil {
			return fail(err)
		}
	}
	region := ""
	if hasRegion {
		q, err := rpcmodel.Query(ctx, in)
		if err != nil {
			return fail(err)
		}
		region = q.Get("RegionId")
	}
	callOptions, err := c.callOptions(region, optFns)
	if err != nil {
		return fail(err)
	}
	codec := alicloud.Codec{
		Encode: func(ctx context.Context, value any) (alicloud.Request, error) {
			if validate != nil {
				if err := validate(value.(*I)); err != nil {
					return alicloud.Request{}, err
				}
			}
			q, form, err := rpcmodel.Parameters(ctx, value)
			if err != nil {
				return alicloud.Request{}, err
			}
			requestRegion := q.Get("RegionId")
			if hasRegion && requestRegion == "" {
				requestRegion = c.runtime.Region()
				q.Set("RegionId", requestRegion)
			}
			if err := ctx.Err(); err != nil {
				return alicloud.Request{}, err
			}
			return alicloud.Request{Method: method, Path: "/", Region: requestRegion, Query: q, Body: []byte(form.Encode()), Header: map[string][]string{"Content-Type": {"application/x-www-form-urlencoded"}}}, nil
		}, Decode: func(ctx context.Context, data []byte, value any) error {
			if err := ctx.Err(); err != nil {
				return err
			}
			return json.Unmarshal(data, value)
		}}
	out := new(O)
	meta, err := c.runtime.InvokeModel(ctx, op, in, alicloud.Request{Region: region}, out, codec, callOptions...)
	if err != nil {
		return nil, meta, err
	}
	return out, meta, nil
}
