// Code generated by sdkgen product; DO NOT EDIT.
package sts

import (
	"context"
	alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"
)

// AssumeRoleAPI is the minimal interface for AssumeRole mocks and capability adapters.
type AssumeRoleAPI interface {
	// AssumeRole invokes the native action with owned inputs and per-call options.
	AssumeRole(context.Context, *AssumeRoleInput, ...func(*Options)) (*AssumeRoleOutput, error)
}

// AssumeRole calls the native AssumeRole action (API version 2015-04-01).
// Nil input is an empty request. Errors preserve cancellation and structured service causes.
// Inputs are deeply copied before hooks; callbacks must not retain options or models.
// Standard never retries this operation under the current conservative policy.
func (c *Client) AssumeRole(ctx context.Context, input *AssumeRoleInput, optFns ...func(*Options)) (*AssumeRoleOutput, error) {
	out, meta, err := invoke[AssumeRoleInput, AssumeRoleOutput](ctx, c, input, alicloud.Operation{Service: "sts", Name: "AssumeRole", Version: "2015-04-01", Idempotent: false}, false, nil, nil, optFns)
	if err != nil {
		return nil, err
	}
	out.Metadata = meta
	return out, nil
}
