// Code generated by sdkgen product; DO NOT EDIT.
package sts

// String hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleInput) String() string { return "AssumeRoleInput (sensitive fields redacted)" }

// GoString hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleInput) GoString() string { return "AssumeRoleInput (sensitive fields redacted)" }

// String hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleResponse) String() string { return "AssumeRoleResponse (sensitive fields redacted)" }

// GoString hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleResponse) GoString() string { return "AssumeRoleResponse (sensitive fields redacted)" }

// String hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleOutput) String() string { return "AssumeRoleOutput (sensitive fields redacted)" }

// GoString hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleOutput) GoString() string { return "AssumeRoleOutput (sensitive fields redacted)" }

// String hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleOutputCredentials) String() string {
	return "AssumeRoleOutputCredentials (sensitive fields redacted)"
}

// GoString hides the complete sensitive model during fmt formatting.
// JSON serialization and direct field access still expose the original data.
func (AssumeRoleOutputCredentials) GoString() string {
	return "AssumeRoleOutputCredentials (sensitive fields redacted)"
}
