// Code generated by sdkgen product; DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// Model definitions derive from pinned Alibaba Cloud Darabonba DSL.
// See sources/darabonba/LICENSE.upstream and the source manifest for attribution.
package sts

import alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"

// AssumeRoleInput represents the complete DSL model AssumeRoleRequest.
// Optional pointers preserve absence; callers must not mutate inputs during a call.
type AssumeRoleInput struct {
	// DurationSeconds maps to the exact wire member DurationSeconds.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	DurationSeconds *int64 `json:"DurationSeconds,omitzero"`
	// ExternalID maps to the exact wire member ExternalId.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	ExternalID *string `json:"ExternalId,omitzero"`
	// Policy maps to the exact wire member Policy.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	Policy *string `json:"Policy,omitzero"`
	// RoleARN maps to the exact wire member RoleArn.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	RoleARN *string `json:"RoleArn,omitzero"`
	// RoleSessionName maps to the exact wire member RoleSessionName.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	RoleSessionName *string `json:"RoleSessionName,omitzero"`
	// SourceIdentity maps to the exact wire member SourceIdentity.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	SourceIdentity *string `json:"SourceIdentity,omitzero"`
}

// AssumeRoleResponse represents the complete DSL model AssumeRoleResponse.
// Optional pointers preserve absence; callers must not mutate inputs during a call.
type AssumeRoleResponse struct {
	// Headers maps to the exact wire member headers.
	Headers map[string]string `json:"headers,omitzero"`
	// StatusCode maps to the exact wire member statusCode.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	StatusCode *int32 `json:"statusCode,omitzero"`
	// Body maps to the exact wire member body.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	Body *AssumeRoleOutput `json:"body,omitzero"`
}

// AssumeRoleOutput represents the complete DSL model AssumeRoleResponseBody.
// Optional pointers preserve absence; callers must not mutate inputs during a call.
type AssumeRoleOutput struct {
	// AssumedRoleUser maps to the exact wire member AssumedRoleUser.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	AssumedRoleUser *AssumeRoleOutputAssumedRoleUser `json:"AssumedRoleUser,omitzero"`
	// Credentials maps to the exact wire member Credentials.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	Credentials *AssumeRoleOutputCredentials `json:"Credentials,omitzero"`
	// RequestID maps to the exact wire member RequestId.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	RequestID *string `json:"RequestId,omitzero"`
	// SourceIdentity maps to the exact wire member SourceIdentity.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	SourceIdentity *string `json:"SourceIdentity,omitzero"`
	// Metadata contains request identity, HTTP status and attempt count.
	Metadata alicloud.Metadata `json:"-"`
}

// AssumeRoleOutputAssumedRoleUser represents the complete DSL model AssumeRoleResponseBody.assumedRoleUser.
// Optional pointers preserve absence; callers must not mutate inputs during a call.
type AssumeRoleOutputAssumedRoleUser struct {
	// ARN maps to the exact wire member Arn.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	ARN *string `json:"Arn,omitzero"`
	// AssumedRoleID maps to the exact wire member AssumedRoleId.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	AssumedRoleID *string `json:"AssumedRoleId,omitzero"`
}

// AssumeRoleOutputCredentials represents the complete DSL model AssumeRoleResponseBody.credentials.
// Optional pointers preserve absence; callers must not mutate inputs during a call.
type AssumeRoleOutputCredentials struct {
	// AccessKeyID maps to the exact wire member AccessKeyId.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	AccessKeyID *string `json:"AccessKeyId,omitzero"`
	// AccessKeySecret maps to the exact wire member AccessKeySecret.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	AccessKeySecret *string `json:"AccessKeySecret,omitzero"`
	// Expiration maps to the exact wire member Expiration.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	Expiration *string `json:"Expiration,omitzero"`
	// SecurityToken maps to the exact wire member SecurityToken.
	// Nil omits this member; non-nil scalar pointers preserve explicit zero values.
	SecurityToken *string `json:"SecurityToken,omitzero"`
}
