// Code generated by sdkgen product; DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2009-present, Alibaba Cloud All rights reserved.
// Modified: pinned DSL endpoint maps converted to Go; reviewed network rules added.
// See LICENSE and NOTICE for source attribution.
package endpoint

func init() {
	defaultEndpointRules = []Rule{
		// Source: products/ecs/main.tea:20.
		{Service: "ecs", Region: "ap-northeast-2-pop", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:21.
		{Service: "ecs", Region: "cn-beijing-finance-pop", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:22.
		{Service: "ecs", Region: "cn-beijing-gov-1", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:23.
		{Service: "ecs", Region: "cn-beijing-nu16-b01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:24.
		{Service: "ecs", Region: "cn-edge-1", URL: "https://ecs.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/ecs/main.tea:25.
		{Service: "ecs", Region: "cn-fujian", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:26.
		{Service: "ecs", Region: "cn-haidian-cm12-c01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:16.
		{Service: "ecs", Region: "cn-hangzhou", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:27.
		{Service: "ecs", Region: "cn-hangzhou-bj-b01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:28.
		{Service: "ecs", Region: "cn-hangzhou-finance", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:29.
		{Service: "ecs", Region: "cn-hangzhou-internal-prod-1", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:30.
		{Service: "ecs", Region: "cn-hangzhou-internal-test-1", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:31.
		{Service: "ecs", Region: "cn-hangzhou-internal-test-2", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:32.
		{Service: "ecs", Region: "cn-hangzhou-internal-test-3", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:33.
		{Service: "ecs", Region: "cn-hangzhou-test-306", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:34.
		{Service: "ecs", Region: "cn-hongkong-finance-pop", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:35.
		{Service: "ecs", Region: "cn-huhehaote-nebula-1", URL: "https://ecs.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/ecs/main.tea:19.
		{Service: "ecs", Region: "cn-north-2-gov-1", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:36.
		{Service: "ecs", Region: "cn-shanghai-et15-b01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:37.
		{Service: "ecs", Region: "cn-shanghai-et2-b01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:17.
		{Service: "ecs", Region: "cn-shanghai-finance-1", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:38.
		{Service: "ecs", Region: "cn-shanghai-inner", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:39.
		{Service: "ecs", Region: "cn-shanghai-internal-test-1", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:18.
		{Service: "ecs", Region: "cn-shenzhen-finance-1", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:40.
		{Service: "ecs", Region: "cn-shenzhen-inner", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:41.
		{Service: "ecs", Region: "cn-shenzhen-st4-d01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:42.
		{Service: "ecs", Region: "cn-shenzhen-su18-b01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:43.
		{Service: "ecs", Region: "cn-wuhan", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:44.
		{Service: "ecs", Region: "cn-yushanfang", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:45.
		{Service: "ecs", Region: "cn-zhangbei", URL: "https://ecs.aliyuncs.com"},
		// Source: products/ecs/main.tea:46.
		{Service: "ecs", Region: "cn-zhangbei-na61-b01", URL: "https://ecs-cn-hangzhou.aliyuncs.com"},
		// Source: products/ecs/main.tea:47.
		{Service: "ecs", Region: "cn-zhangjiakou-na62-a01", URL: "https://ecs.cn-zhangjiakou.aliyuncs.com"},
		// Source: products/ecs/main.tea:48.
		{Service: "ecs", Region: "cn-zhengzhou-nebula-1", URL: "https://ecs.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/ecs/main.tea:49.
		{Service: "ecs", Region: "eu-west-1-oxs", URL: "https://ecs.cn-shenzhen-cloudstone.aliyuncs.com"},
		// Source: products/ecs/main.tea:50.
		{Service: "ecs", Region: "rus-west-1-pop", URL: "https://ecs.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-beijing", Network: "vpc", URL: "https://ecs-vpc.cn-beijing.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-fuzhou", Network: "vpc", URL: "https://ecs-vpc.cn-fuzhou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-hangzhou", Network: "vpc", URL: "https://ecs-vpc.cn-hangzhou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-nanjing", Network: "vpc", URL: "https://ecs-vpc.cn-nanjing.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-qingdao", Network: "vpc", URL: "https://ecs-vpc.cn-qingdao.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-shanghai", Network: "vpc", URL: "https://ecs-vpc.cn-shanghai.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "cn-zhangjiakou", Network: "vpc", URL: "https://ecs-vpc.cn-zhangjiakou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "eu-west-1", Network: "vpc", URL: "https://ecs-vpc.eu-west-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "me-east-1", Network: "vpc", URL: "https://ecs-vpc.me-east-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "us-east-1", Network: "vpc", URL: "https://ecs-vpc.us-east-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ecs/developer-reference/call-api-operations-over-the-internal-network.
		{Service: "ecs", Region: "us-west-1", Network: "vpc", URL: "https://ecs-vpc.us-west-1.aliyuncs.com"},
		// Source: products/sts/main.tea:16.
		{Service: "sts", Region: "ap-northeast-2-pop", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:17.
		{Service: "sts", Region: "ap-south-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:18.
		{Service: "sts", Region: "ap-southeast-2", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:19.
		{Service: "sts", Region: "cn-beijing-finance-pop", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:20.
		{Service: "sts", Region: "cn-beijing-gov-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:21.
		{Service: "sts", Region: "cn-beijing-nu16-b01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:22.
		{Service: "sts", Region: "cn-edge-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:23.
		{Service: "sts", Region: "cn-fujian", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:24.
		{Service: "sts", Region: "cn-haidian-cm12-c01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:25.
		{Service: "sts", Region: "cn-hangzhou-bj-b01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:26.
		{Service: "sts", Region: "cn-hangzhou-internal-prod-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:27.
		{Service: "sts", Region: "cn-hangzhou-internal-test-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:28.
		{Service: "sts", Region: "cn-hangzhou-internal-test-2", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:29.
		{Service: "sts", Region: "cn-hangzhou-internal-test-3", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:30.
		{Service: "sts", Region: "cn-hangzhou-test-306", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:31.
		{Service: "sts", Region: "cn-hongkong-finance-pop", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:32.
		{Service: "sts", Region: "cn-huhehaote-nebula-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:33.
		{Service: "sts", Region: "cn-shanghai-et15-b01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:34.
		{Service: "sts", Region: "cn-shanghai-et2-b01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:35.
		{Service: "sts", Region: "cn-shanghai-inner", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:36.
		{Service: "sts", Region: "cn-shanghai-internal-test-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:37.
		{Service: "sts", Region: "cn-shenzhen-inner", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:38.
		{Service: "sts", Region: "cn-shenzhen-st4-d01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:39.
		{Service: "sts", Region: "cn-shenzhen-su18-b01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:40.
		{Service: "sts", Region: "cn-wuhan", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:41.
		{Service: "sts", Region: "cn-yushanfang", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:42.
		{Service: "sts", Region: "cn-zhangbei", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:43.
		{Service: "sts", Region: "cn-zhangbei-na61-b01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:44.
		{Service: "sts", Region: "cn-zhangjiakou-na62-a01", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:45.
		{Service: "sts", Region: "cn-zhengzhou-nebula-1", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:46.
		{Service: "sts", Region: "eu-west-1-oxs", URL: "https://sts.aliyuncs.com"},
		// Source: products/sts/main.tea:47.
		{Service: "sts", Region: "rus-west-1-pop", URL: "https://sts.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-northeast-1", Network: "vpc", URL: "https://sts-vpc.ap-northeast-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-northeast-2", Network: "vpc", URL: "https://sts-vpc.ap-northeast-2.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-southeast-1", Network: "vpc", URL: "https://sts-vpc.ap-southeast-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-southeast-3", Network: "vpc", URL: "https://sts-vpc.ap-southeast-3.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-southeast-5", Network: "vpc", URL: "https://sts-vpc.ap-southeast-5.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-southeast-7", Network: "vpc", URL: "https://sts-vpc.ap-southeast-7.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "ap-southeast-8", Network: "vpc", URL: "https://sts-vpc.ap-southeast-8.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-beijing", Network: "vpc", URL: "https://sts-vpc.cn-beijing.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-beijing-finance-1", Network: "vpc", URL: "https://sts-vpc.cn-beijing-finance-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-chengdu", Network: "vpc", URL: "https://sts-vpc.cn-chengdu.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-fuzhou", Network: "vpc", URL: "https://sts-vpc.cn-fuzhou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-guangzhou", Network: "vpc", URL: "https://sts-vpc.cn-guangzhou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-hangzhou", Network: "vpc", URL: "https://sts-vpc.cn-hangzhou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-heyuan", Network: "vpc", URL: "https://sts-vpc.cn-heyuan.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-hongkong", Network: "vpc", URL: "https://sts-vpc.cn-hongkong.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-huhehaote", Network: "vpc", URL: "https://sts-vpc.cn-huhehaote.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-nanjing", Network: "vpc", URL: "https://sts-vpc.cn-nanjing.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-qingdao", Network: "vpc", URL: "https://sts-vpc.cn-qingdao.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-shanghai", Network: "vpc", URL: "https://sts-vpc.cn-shanghai.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-shanghai-finance-1", Network: "vpc", URL: "https://sts-vpc.cn-shanghai-finance-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-shenzhen", Network: "vpc", URL: "https://sts-vpc.cn-shenzhen.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-shenzhen-finance-1", Network: "vpc", URL: "https://sts-vpc.cn-shenzhen-finance-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-wuhan-lr", Network: "vpc", URL: "https://sts-vpc.cn-wuhan-lr.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-wulanchabu", Network: "vpc", URL: "https://sts-vpc.cn-wulanchabu.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-zhangjiakou", Network: "vpc", URL: "https://sts-vpc.cn-zhangjiakou.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "cn-zhongwei", Network: "vpc", URL: "https://sts-vpc.cn-zhongwei.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "eu-central-1", Network: "vpc", URL: "https://sts-vpc.eu-central-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "eu-west-1", Network: "vpc", URL: "https://sts-vpc.eu-west-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "eu-west-2", Network: "vpc", URL: "https://sts-vpc.eu-west-2.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "me-central-1", Network: "vpc", URL: "https://sts-vpc.me-central-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "me-east-1", Network: "vpc", URL: "https://sts-vpc.me-east-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "na-south-1", Network: "vpc", URL: "https://sts-vpc.na-south-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "sa-east-1", Network: "vpc", URL: "https://sts-vpc.sa-east-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "us-east-1", Network: "vpc", URL: "https://sts-vpc.us-east-1.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/ram/developer-reference/api-sts-2015-04-01-endpoint.
		{Service: "sts", Region: "us-west-1", Network: "vpc", URL: "https://sts-vpc.us-west-1.aliyuncs.com"},
		// Source: products/vpc/main.tea:20.
		{Service: "vpc", Region: "ap-northeast-2-pop", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:21.
		{Service: "vpc", Region: "cn-beijing-finance-pop", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:22.
		{Service: "vpc", Region: "cn-beijing-gov-1", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:23.
		{Service: "vpc", Region: "cn-beijing-nu16-b01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:24.
		{Service: "vpc", Region: "cn-edge-1", URL: "https://vpc-nebula.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/vpc/main.tea:25.
		{Service: "vpc", Region: "cn-fujian", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:26.
		{Service: "vpc", Region: "cn-haidian-cm12-c01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:16.
		{Service: "vpc", Region: "cn-hangzhou", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:27.
		{Service: "vpc", Region: "cn-hangzhou-bj-b01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:28.
		{Service: "vpc", Region: "cn-hangzhou-finance", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:29.
		{Service: "vpc", Region: "cn-hangzhou-internal-prod-1", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:30.
		{Service: "vpc", Region: "cn-hangzhou-internal-test-1", URL: "https://vpc-pre.cn-hangzhou.aliyuncs.com"},
		// Source: products/vpc/main.tea:31.
		{Service: "vpc", Region: "cn-hangzhou-internal-test-2", URL: "https://vpc-inner-pre.cn-hangzhou.aliyuncs.com"},
		// Source: products/vpc/main.tea:32.
		{Service: "vpc", Region: "cn-hangzhou-internal-test-3", URL: "https://vpc-pre.cn-hangzhou.aliyuncs.com"},
		// Source: products/vpc/main.tea:33.
		{Service: "vpc", Region: "cn-hangzhou-test-306", URL: "https://vpc-pre.cn-hangzhou.aliyuncs.com"},
		// Source: products/vpc/main.tea:34.
		{Service: "vpc", Region: "cn-hongkong-finance-pop", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:35.
		{Service: "vpc", Region: "cn-huhehaote-nebula-1", URL: "https://vpc-nebula.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/vpc/main.tea:19.
		{Service: "vpc", Region: "cn-north-2-gov-1", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:36.
		{Service: "vpc", Region: "cn-qingdao-nebula", URL: "https://vpc-nebula.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/vpc/main.tea:37.
		{Service: "vpc", Region: "cn-shanghai-et15-b01", URL: "https://vpc-pre.cn-hangzhou.aliyuncs.com"},
		// Source: products/vpc/main.tea:38.
		{Service: "vpc", Region: "cn-shanghai-et2-b01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:17.
		{Service: "vpc", Region: "cn-shanghai-finance-1", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:39.
		{Service: "vpc", Region: "cn-shanghai-inner", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:40.
		{Service: "vpc", Region: "cn-shanghai-internal-test-1", URL: "https://vpc-pre.cn-hangzhou.aliyuncs.com"},
		// Source: products/vpc/main.tea:18.
		{Service: "vpc", Region: "cn-shenzhen-finance-1", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:41.
		{Service: "vpc", Region: "cn-shenzhen-inner", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:42.
		{Service: "vpc", Region: "cn-shenzhen-st4-d01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:43.
		{Service: "vpc", Region: "cn-shenzhen-su18-b01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:44.
		{Service: "vpc", Region: "cn-wuhan", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:45.
		{Service: "vpc", Region: "cn-yushanfang", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:46.
		{Service: "vpc", Region: "cn-zhangbei", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:47.
		{Service: "vpc", Region: "cn-zhangbei-na61-b01", URL: "https://vpc.aliyuncs.com"},
		// Source: products/vpc/main.tea:48.
		{Service: "vpc", Region: "cn-zhangjiakou-na62-a01", URL: "https://vpc.cn-zhangjiakou.aliyuncs.com"},
		// Source: products/vpc/main.tea:49.
		{Service: "vpc", Region: "cn-zhengzhou-nebula-1", URL: "https://vpc-nebula.cn-qingdao-nebula.aliyuncs.com"},
		// Source: products/vpc/main.tea:50.
		{Service: "vpc", Region: "eu-west-1-oxs", URL: "https://vpc-nebula.cn-shenzhen-cloudstone.aliyuncs.com"},
		// Source: products/vpc/main.tea:51.
		{Service: "vpc", Region: "rus-west-1-pop", URL: "https://vpc.aliyuncs.com"},
		// Reviewed source: https://www.alibabacloud.com/help/en/vpc/use-privatelink-to-access-vpc-openapi-over-private-network.
		{Service: "vpc", Region: "cn-beijing", Network: "vpc", URL: "https://vpc-vpc.cn-beijing.aliyuncs.com"},
	}
	defaultDeploymentRules = map[string]deploymentRule{
		"ecs": {productCode: "ecs", kind: "regional"},
		"sts": {productCode: "sts", kind: "regional"},
		"vpc": {productCode: "vpc", kind: "regional"},
	}
}
