package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

const generated = "// Code generated by sdkgen; DO NOT EDIT.\n"
const module = "github.com/rambow-cloud/alicloud-go-sdk-x"

// Render produces the entire owned file set without touching the filesystem.
func Render(p Product) (map[string][]byte, error) {
	files := map[string][]byte{}
	base := "services/" + p.Manifest.Package + "/"
	code, err := emitClient(p)
	if err != nil {
		return nil, err
	}
	files[base+"sdk.gen.go"] = code
	code, err = emitExamples(p)
	if err != nil {
		return nil, err
	}
	files[base+"examples.gen_test.go"] = code
	var doc strings.Builder
	doc.WriteString(generated)
	doc.WriteString("\n")
	fmt.Fprintf(&doc, "// Package %s %s\npackage %s\n", p.Manifest.Package, lowerFirst(p.Overlay.Doc.English), p.Manifest.Package)
	code, err = format.Source([]byte(doc.String()))
	if err != nil {
		return nil, err
	}
	files[base+"doc.go"] = code
	if len(p.Overlay.paginatorSpecs()) > 0 || len(p.Overlay.waiterSpecs()) > 0 {
		code, err = emitAdapters(p)
		if err != nil {
			return nil, err
		}
		files[base+"adapters.gen.go"] = code
	}
	files["docs/generated/"+p.Manifest.Package+".md"] = emitGuide(p)
	return files, nil
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
func quote(s string) string { return strconv.Quote(s) }

func preamble(b *bytes.Buffer, pkg string, imports map[string]string) {
	b.WriteString(generated)
	fmt.Fprintf(b, "package %s\n\nimport (\n", pkg)
	for _, path := range sortedKeys(imports) {
		fmt.Fprintf(b, "%s %q\n", imports[path], path)
	}
	b.WriteString(")\n\n")
}

func emitClient(p Product) ([]byte, error) {
	imports := map[string]string{"context": "", "errors": "", "encoding/json/v2": "", "net/url": "", module: "alicloud"}
	for _, model := range p.Models {
		for _, f := range model.Fields {
			if strings.TrimPrefix(strings.TrimPrefix(f.Type, "[]"), "*") == "time.Time" {
				imports["time"] = ""
			}
			if strings.Contains(f.Wire, ".") {
				imports["encoding/json/v2"] = ""
			}
		}
	}
	for _, op := range p.Operations {
		if op.InputRequired {
			imports["errors"] = ""
		}
		for _, f := range op.Outputs {
			if strings.TrimPrefix(strings.TrimPrefix(f.Type, "[]"), "*") == "time.Time" {
				imports["time"] = ""
			}
		}
		for _, f := range op.Inputs {
			if (f.Required && !f.Region) || f.Minimum != nil || f.Maximum != nil || f.MaxItems > 0 {
				imports["errors"] = ""
			}
			if strings.TrimPrefix(f.Type, "*") == "int" || strings.TrimPrefix(f.Type, "*") == "int64" || f.Type == "*bool" || f.Encoding == "repeatList" {
				imports["strconv"] = ""
			}
			if f.Encoding == "jsonArray" {
				imports["encoding/json/v2"] = ""
			}
			if strings.HasPrefix(f.Type, "[]") {
				for _, m := range p.Models {
					if m.Location == "input" && m.Name == strings.TrimPrefix(f.Type, "[]") {
						for _, member := range m.Fields {
							if member.Required || member.Minimum != nil || member.Maximum != nil {
								imports["errors"] = ""
							}
						}
					}
				}
			}
		}
	}
	var b bytes.Buffer
	imports[module+"/middleware"] = ""
	preamble(&b, p.Manifest.Package, imports)
	b.WriteString("// Options configures this service and individual calls. Fields follow alicloud.Config.\n// Options values are copied; extension objects must be concurrency safe.\ntype Options alicloud.Config\n")
	fmt.Fprintf(&b, "// Client is a concurrency-safe %s client. Construct it with NewFromConfig or New.\ntype Client struct { runtime *alicloud.Client }\n", p.Manifest.Product)
	b.WriteString("// New validates shared configuration and applies service options.\n// It is the convenience alias of NewFromConfig.\nfunc New(config alicloud.Config,opts ...func(*Options))(*Client,error){return NewFromConfig(config,opts...)}\n")
	b.WriteString("// NewFromConfig copies configuration and applies service options before validation.\n// Providers, transports and hooks remain shared and must be concurrency safe.\nfunc NewFromConfig(config alicloud.Config,opts ...func(*Options))(*Client,error){o:=Options(config);o.Middleware=append([]middleware.Registration(nil),o.Middleware...);for _,f:=range opts{if f==nil{return nil,errors.New(\"nil service option\")};f(&o)};c,err:=alicloud.NewClient(alicloud.Config(o));if err!=nil{return nil,err};return &Client{runtime:c},nil}\n")
	b.WriteString("// Options returns a configuration snapshot with copied middleware registrations.\n// Extension objects remain shared; changing this value never changes the client.\nfunc(c *Client)Options()Options{return Options(c.runtime.Config())}\n")
	b.WriteString("func(c *Client)callOptions(region string,opts []func(*Options))([]func(*alicloud.CallOptions),error){if len(opts)==0{return nil,nil};o:=c.Options();if region!=\"\"{o.Region=region};for _,f:=range opts{if f==nil{return nil,errors.New(\"nil call option\")};f(&o)};config:=alicloud.Config(o);return []func(*alicloud.CallOptions){func(call *alicloud.CallOptions){call.Config=&config;call.Region=o.Region}},nil}\n")

	for _, m := range p.Models {
		fmt.Fprintf(&b, "// %s %s\ntype %s struct {\n", m.Name, lowerFirst(m.Doc.English), m.Name)
		for _, f := range m.Fields {
			fmt.Fprintf(&b, "// %s %s\n", f.Name, lowerFirst(f.Doc.English))
			if m.Location == "input" {
				emitPresenceDoc(&b, f)
			}
			fmt.Fprintf(&b, "%s %s `json:%s`\n", f.Name, f.Type, quote(f.Wire))
		}
		b.WriteString("}\n")
		if m.Location == "input" {
			fmt.Fprintf(&b, "func clone%s(in %s)%s{out:=in\n", m.Name, m.Name, m.Name)
			copySlices(&b, m.Fields, "out", "in", p.Models)
			b.WriteString("return out}\n")
		}
		if hasNested(m.Fields) {
			emitModelJSON(&b, m)
		}
		if m.Redact {
			fmt.Fprintf(&b, "// String returns a redacted representation.\nfunc (%s) String()string{return %q}\n// GoString returns a redacted representation for Go formatting.\nfunc(c %s)GoString()string{return c.String()}\n", m.Name, m.Name+"(<redacted>)", m.Name)
		}
	}
	for _, op := range p.Operations {
		fmt.Fprintf(&b, "// %sInput contains the selected query parameters; zero optional values are omitted.\ntype %sInput struct {\n", op.Name, op.Name)
		for _, f := range op.Inputs {
			fmt.Fprintf(&b, "// %s %s\n", f.Name, lowerFirst(f.Doc.English))
			emitPresenceDoc(&b, f)
			if f.Required && !f.Region {
				b.WriteString("// This field is required.\n")
			}
			if f.Minimum != nil {
				if strings.HasPrefix(f.Type, "*") {
					fmt.Fprintf(&b, "// Present values must be at least %d.\n", *f.Minimum)
				} else {
					fmt.Fprintf(&b, "// Nonzero values must be at least %d.\n", *f.Minimum)
				}
			}
			if f.Maximum != nil {
				if strings.HasPrefix(f.Type, "*") {
					fmt.Fprintf(&b, "// Present values must be at most %d.\n", *f.Maximum)
				} else {
					fmt.Fprintf(&b, "// Nonzero values must be at most %d.\n", *f.Maximum)
				}
			}
			fmt.Fprintf(&b, "%s %s\n", f.Name, f.Type)
		}
		b.WriteString("}\n")
		fmt.Fprintf(&b, "// %sOutput contains selected response fields and transport metadata.\ntype %sOutput struct {\n", op.Name, op.Name)
		for _, f := range op.Outputs {
			fmt.Fprintf(&b, "// %s %s\n%s %s", f.Name, lowerFirst(f.Doc.English), f.Name, f.Type)
			if !strings.Contains(f.Wire, ".") {
				fmt.Fprintf(&b, " `json:%s`", quote(f.Wire))
			}
			b.WriteString("\n")
		}
		b.WriteString("// Metadata contains request ID, status and attempt count; it is excluded from wire decoding.\nMetadata alicloud.Metadata `json:\"-\"`\n}\n")
		fmt.Fprintf(&b, "// %sAPI is the minimal operation interface for consumers and fakes.\ntype %sAPI interface {\n// %s %s\n%s(context.Context,*%sInput,...func(*Options))(*%sOutput,error)\n}\n", op.Name, op.Name, op.Name, lowerFirst(op.Doc.English), op.Name, op.Name, op.Name)
		if err := emitOperation(&b, p, op); err != nil {
			return nil, err
		}
	}
	fmt.Fprintf(&b, "func generatedValidation(ctx context.Context,name string,err error)error{if ctx.Err()!=nil{err=ctx.Err()};return &alicloud.OperationError{Service:%q,Operation:name,Err:err}}\n", p.Manifest.Service)
	data, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format client %s: %w", p.Manifest.Package, err)
	}
	return data, nil
}

func copySlices(b *bytes.Buffer, fields []Field, dst, src string, models ...[]Model) {
	for _, f := range fields {
		if f.Type == "[]string" {
			fmt.Fprintf(b, "%s.%s=append([]string(nil),%s.%s...)\n", dst, f.Name, src, f.Name)
		}
		if strings.HasPrefix(f.Type, "*") {
			fmt.Fprintf(b, "if %s.%s!=nil{copied:=*%s.%s;%s.%s=&copied}\n", src, f.Name, src, f.Name, dst, f.Name)
		}
		if strings.HasPrefix(f.Type, "[]") && f.Type != "[]string" && len(models) > 0 {
			for _, m := range models[0] {
				if m.Name == strings.TrimPrefix(f.Type, "[]") && m.Location == "input" {
					fmt.Fprintf(b, "%s.%s=append([]%s(nil),%s.%s...)\nfor i:=range %s.%s{%s.%s[i]=clone%s(%s.%s[i])}\n", dst, f.Name, m.Name, src, f.Name, dst, f.Name, dst, f.Name, m.Name, dst, f.Name)
				}
			}
		}
	}
}

type wireNode struct {
	typ      string
	children map[string]*wireNode
	goName   string
}

func wireTree(fields []Field) *wireNode {
	root := &wireNode{children: map[string]*wireNode{}}
	for _, f := range fields {
		node := root
		for _, part := range strings.Split(f.Wire, ".") {
			if node.children == nil {
				node.children = map[string]*wireNode{}
			}
			if node.children[part] == nil {
				node.children[part] = &wireNode{}
			}
			node = node.children[part]
		}
		node.typ = f.Type
	}
	return root
}
func emitWire(b *bytes.Buffer, node *wireNode) {
	b.WriteString("struct {\n")
	for i, key := range sortedKeys(node.children) {
		child := node.children[key]
		child.goName = "W" + strconv.Itoa(i)
		fmt.Fprintf(b, "%s ", child.goName)
		if child.typ != "" {
			b.WriteString(child.typ)
		} else {
			emitWire(b, child)
		}
		fmt.Fprintf(b, " `json:%s`\n", quote(key))
	}
	b.WriteString("}")
}
func wireAccess(root *wireNode, path string) string {
	value := "wire"
	for _, part := range strings.Split(path, ".") {
		root = root.children[part]
		value += "." + root.goName
	}
	return value
}

func emitOperation(b *bytes.Buffer, p Product, op Operation) error {
	fmt.Fprintf(b, "// %s %s\n// API version %s. Errors preserve cancellation and structured service causes.\n", op.Name, lowerFirst(op.Doc.English), p.Manifest.Version)
	if !*op.Idempotent {
		b.WriteString("// This operation is conservatively non-idempotent and is not retried by Standard.\n")
	}
	fmt.Fprintf(b, "func(c *Client)%s(ctx context.Context,input *%sInput,opts ...func(*Options))(*%sOutput,error){\n", op.Name, op.Name, op.Name)
	fmt.Fprintf(b, "fail:=func(err error)(*%sOutput,error){return nil,generatedValidation(ctx,%q,err)}\n", op.Name, op.Name)
	b.WriteString("if err:=ctx.Err();err!=nil{return fail(err)}\n")
	if op.InputRequired {
		b.WriteString("if input==nil{return fail(errors.New(\"input required\"))}\n")
	}
	fmt.Fprintf(b, "var in %sInput\nif input!=nil{in=*input\n", op.Name)
	copySlices(b, op.Inputs, "in", "input", p.Models)
	b.WriteString("}\n")
	b.WriteString("requestRegion:=\"\"\n")
	for _, f := range op.Inputs {
		if f.Region {
			fmt.Fprintf(b, "requestRegion=in.%s\n", f.Name)
		}
	}
	b.WriteString("callOptions,err:=c.callOptions(requestRegion,opts);if err!=nil{return fail(err)}\n")
	fmt.Fprintf(b, "codec:=alicloud.Codec{Encode:func(ctx context.Context,value any)(alicloud.Request,error){in:=*value.(*%sInput)\n", op.Name)
	copySlices(b, op.Inputs, "in", "in", p.Models)
	b.WriteString("fail:=func(err error)(alicloud.Request,error){return alicloud.Request{},err}\n_ = fail\n")
	if op.Validator != "" {
		fmt.Fprintf(b, "if err:=%s(in);err!=nil{return fail(err)}\n", op.Validator)
	}
	b.WriteString("region:=\"\"\nq:=url.Values{}\n")
	for _, f := range op.Inputs {
		value := "in." + f.Name
		if f.Region {
			fmt.Fprintf(b, "region=%s;if region==\"\"{region=c.runtime.Region()};q.Set(%q,region)\n", value, f.Wire)
			continue
		}
		if !strings.HasPrefix(f.Type, "[]") {
			emitQueryField(b, f, value, quote(f.Wire))
			continue
		}
		if f.Required {
			fmt.Fprintf(b, "if len(%s)==0{return fail(errors.New(%q))}\n", value, "required parameter "+f.Wire)
		}
		if f.MaxItems > 0 {
			fmt.Fprintf(b, "if len(%s)>%d{return fail(errors.New(%q))}\n", value, f.MaxItems, "array too large: "+f.Wire)
		}
		if f.Type == "[]string" {
			if f.Encoding == "jsonArray" {
				fmt.Fprintf(b, "if len(%s)>0{encoded,err:=json.Marshal(%s);if err!=nil{return fail(err)};q.Set(%q,string(encoded))}\n", value, value, f.Wire)
			} else {
				fmt.Fprintf(b, "for i,value:=range %s{q.Set(%q+strconv.Itoa(i+1),value)}\n", value, f.Wire+".")
			}
		} else {
			for _, m := range p.Models {
				if m.Name == strings.TrimPrefix(f.Type, "[]") {
					fmt.Fprintf(b, "for i,item:=range %s{prefix:=%q+strconv.Itoa(i+1)+\".\"\n", value, f.Wire+".")
					for _, member := range m.Fields {
						emitQueryField(b, member, "item."+member.Name, "prefix+"+quote(member.Wire))
					}
					b.WriteString("}\n")
				}
			}
		}
	}
	method, path := "POST", "/"
	if op.Protocol.Method != "" {
		method, path = op.Protocol.Method, op.Protocol.Path
	}
	fmt.Fprintf(b, "return alicloud.Request{Method:%q,Path:%q,Region:region,Query:q,Header:map[string][]string{\"Content-Type\":{\"application/x-www-form-urlencoded\"}}},nil},Decode:func(ctx context.Context,data []byte,value any)error{\n", method, path)
	root := wireTree(op.Outputs)
	b.WriteString("var wire ")
	emitWire(b, root)
	b.WriteString("\nif err:=json.Unmarshal(data,&wire);err!=nil{return err}\n")
	fmt.Fprintf(b, "*value.(*%sOutput)=%sOutput{", op.Name, op.Name)
	for _, f := range op.Outputs {
		fmt.Fprintf(b, "%s:%s,", f.Name, wireAccess(root, f.Wire))
	}
	b.WriteString("};return nil}}\n")
	action, version := op.Name, p.Manifest.Version
	if op.Protocol.Action != "" {
		action, version = op.Protocol.Action, op.Protocol.Version
	}
	fmt.Fprintf(b, "out:=new(%sOutput)\nmeta,err:=c.runtime.InvokeModel(ctx,alicloud.Operation{Service:%q,Name:%q,Version:%q,Idempotent:%t},&in,alicloud.Request{Region:requestRegion},out,codec,callOptions...)\nif err!=nil{return nil,err};out.Metadata=meta;return out,nil\n}\n", op.Name, p.Manifest.Service, action, version, *op.Idempotent)
	return nil
}

func emitExamples(p Product) ([]byte, error) {
	var b bytes.Buffer
	preamble(&b, p.Manifest.Package+"_test", map[string]string{"context": "", "fmt": "", "net/http": "", module: "alicloud", module + "/credentials": "", module + "/sdktest": "", module + "/services/" + p.Manifest.Package: ""})
	for _, op := range p.Operations {
		fmt.Fprintf(&b, "func ExampleClient_%s_generated(){\n", op.Name)
		b.WriteString("provider,err:=credentials.NewStaticProvider(credentials.Credentials{AccessKeyID:\"placeholder\",AccessKeySecret:\"placeholder\"});if err!=nil{panic(err)}\n")
		fmt.Fprintf(&b, "transport:=sdktest.NewTransport(sdktest.Step{Body:%q})\n", op.Example.Response)
		fmt.Fprintf(&b, "client,err:=%s.New(alicloud.Config{Region:\"cn-hangzhou\",BaseEndpoint:\"https://example.invalid\",CredentialsProvider:provider,HTTPClient:&http.Client{Transport:transport}});if err!=nil{panic(err)}\n", p.Manifest.Package)
		fmt.Fprintf(&b, "out,err:=client.%s(context.Background(),&%s.%sInput{", op.Name, p.Manifest.Package, op.Name)
		for _, name := range sortedKeys(op.Example.Input) {
			fmt.Fprintf(&b, "%s:", name)
			fields := map[string]Field{}
			for _, f := range op.Inputs {
				fields[f.Name] = f
			}
			models := map[string]ModelSpec{}
			for _, m := range p.Models {
				models[m.Name] = m.ModelSpec
			}
			literal, err := exampleLiteral(fields[name].Type, op.Example.Input[name], p.Manifest.Package, models)
			if err != nil {
				return nil, err
			}
			b.WriteString(literal)
			b.WriteString(",")
		}
		fmt.Fprintf(&b, "});if err!=nil{panic(err)}\nfmt.Println(out.%s)\n// Output: %s\n}\n", op.Example.Print, op.Example.Output)
	}
	return format.Source(b.Bytes())
}

func emitGuide(p Product) []byte {
	var b bytes.Buffer
	b.WriteString("<!-- Code generated by sdkgen; DO NOT EDIT. -->\n")
	fmt.Fprintf(&b, "# %s generated API / %s 生成 API\n\n## English\n\n%s\n\n", p.Manifest.Product, p.Manifest.Product, p.Overlay.Doc.English)
	emitGuideLanguage(&b, p, false)
	b.WriteString("\n## 中文\n\n" + p.Overlay.Doc.Chinese + "\n\n")
	emitGuideLanguage(&b, p, true)
	return b.Bytes()
}

func emitGuideLanguage(b *bytes.Buffer, p Product, chinese bool) {
	if p.DSL != nil {
		if chinese {
			fmt.Fprintf(b, "官方 DSL（revision `%s`）通过 Darabonba parser `%s` 的完整模块语义检查，协议/绑定/选定模型与公共元数据及审核策略共同进入 IR。来源、限制与偏差见 [Darabonba 迁移](../darabonba-migration.md) 和 [决策记录](../darabonba-decisions.md)。\n\n", p.DSL.Revision, p.DSL.ParserVersion)
		} else {
			fmt.Fprintf(b, "Official DSL at revision `%s` passes full imported-module semantic checks with Darabonba parser `%s`. Protocol, bindings and selected models join public metadata and reviewed policy in the IR. See [Darabonba migration](../darabonba-migration.md) and [decisions](../darabonba-decisions.md) for provenance, limits and discrepancies.\n\n", p.DSL.Revision, p.DSL.ParserVersion)
		}
	}
	if chinese {
		b.WriteString("NewFromConfig/保留的 New 接收共享 Config 和服务 functional options，校验后返回客户端与 error。服务 Options 是独立类型，Client.Options 返回配置快照。调用选项（含重试/transport）只作用于当前调用；模型编码前运行 Initialize/Serialize，Deserialize hook 可访问类型化输出。默认重试/超时/凭据规则保持，迁移见 [runtime](../runtime.md) 和 [修复路径](../aws-style-remediation.md)。\n\n")
	} else {
		b.WriteString("NewFromConfig and the retained New accept shared Config and service functional options, returning a validated client and error. Service Options is concrete; Client.Options returns a configuration snapshot. Call options including retries/transports remain isolated. Initialize/Serialize precede model encoding; Deserialize hooks expose typed output. Default retry/timeout/credential policies remain; see [runtime](../runtime.md) and [migration](../aws-style-remediation.md).\n\n")
	}
	if chinese {
		fmt.Fprintf(b, "API 版本 `%s`，协议 RPC/HTTPS/POST；只有审核操作可幂等重试。端点由共享 resolver 决定，元数据不自动扩大地域范围。分页使用审核 token/页码规则；waiter 等待所有指定 ID，缺失/过渡状态继续，未知或重复状态及 API 错误失败。仅配置了相应 overlay 时生成适配器。\n\n", p.Manifest.Version)
	} else {
		fmt.Fprintf(b, "API version `%s`; RPC/HTTPS/POST. Only explicitly reviewed idempotent operations permit retries. Endpoints use the shared resolver; metadata does not expand region coverage. Pagination follows reviewed token/page policies. Waiters require all requested IDs, retry missing/transitional states and fail unknown/duplicate states or API errors. Adapters are emitted only when configured in the overlay.\n\n", p.Manifest.Version)
	}
	for _, pager := range p.Overlay.paginatorSpecs() {
		fmt.Fprintf(b, "`%sPaginator`: ", pager.Operation)
		if pager.Mode == "pages" {
			if chinese {
				fmt.Fprintf(b, "分页仅使用页码，默认页 1/大小 %d；空页或总数到达时结束。\n\n", pager.DefaultSize)
			} else {
				fmt.Fprintf(b, "Pagination is page-only, defaulting to page 1/size %d; empty pages or reaching the total end traversal.\n\n", pager.DefaultSize)
			}
		} else if pager.Mode == "tokens" {
			if chinese {
				b.WriteString("分页仅使用服务原生 token；空条目仍可继续，空 token 结束。\n\n")
			} else {
				b.WriteString("Pagination uses native tokens only; empty items may continue and an empty token ends traversal.\n\n")
			}
		} else {
			if chinese {
				b.WriteString("分页默认 token 模式，显式页码或大小选择旧页码模式。\n\n")
			} else {
				b.WriteString("Pagination defaults to token mode; explicit page/size selects legacy pages.\n\n")
			}
		}
	}
	for _, policy := range p.Overlay.waiterSpecs() {
		if chinese {
			fmt.Fprintf(b, "`%s` 仅绑定 API/专属选项；Wait(ctx,input,maxWait,opts...) 返回 error，WaitForOutput 返回成功输出。每次等待独立复制输入/选项，可并发复用；ClientOptions 每轮生效，Retryable 可覆盖默认 acceptor。详见 [waiter 与迁移](../waiters.md)。\n\n", policy.Name)
		} else {
			fmt.Fprintf(b, "`%s` binds only API/dedicated options; Wait(ctx,input,maxWait,opts...) returns error and WaitForOutput returns the successful output. Waits copy input/options independently and may share the waiter concurrently. ClientOptions applies per poll; Retryable overrides default acceptance. See [waiters and migration](../waiters.md).\n\n", policy.Name)
		}
	}
	for _, op := range p.Operations {
		fmt.Fprintf(b, "### %s\n\n", op.Name)
		if chinese {
			fmt.Fprintf(b, "%s 输入必填：`%t`；幂等：`%t`。\n\n", op.Doc.Chinese, op.InputRequired, *op.Idempotent)
		} else {
			fmt.Fprintf(b, "%s Input required: `%t`; idempotent: `%t`.\n\n", op.Doc.English, op.InputRequired, *op.Idempotent)
		}
		for _, group := range []struct {
			name   string
			fields []Field
		}{{"Input", op.Inputs}, {"Output", op.Outputs}} {
			fmt.Fprintf(b, "| %s | Go | Wire | %s |\n| --- | --- | --- | --- |\n", group.name, map[bool]string{false: "Guidance", true: "说明"}[chinese])
			for _, f := range group.fields {
				doc := f.Doc.English
				if chinese {
					doc = f.Doc.Chinese
				}
				if f.Required && !f.Region {
					if chinese {
						doc += " 必填。"
					} else {
						doc += " Required."
					}
				}
				if strings.HasPrefix(f.Type, "*") {
					if chinese {
						doc += " nil 省略，非 nil 保留显式零值。"
					} else {
						doc += " Nil omits; non-nil preserves explicit zero."
					}
				}
				if f.Minimum != nil {
					if chinese {
						if strings.HasPrefix(f.Type, "*") {
							doc += fmt.Sprintf(" 存在时最小值 %d。", *f.Minimum)
						} else {
							doc += fmt.Sprintf(" 非零最小值 %d。", *f.Minimum)
						}
					} else {
						if strings.HasPrefix(f.Type, "*") {
							doc += fmt.Sprintf(" Present minimum %d.", *f.Minimum)
						} else {
							doc += fmt.Sprintf(" Nonzero minimum %d.", *f.Minimum)
						}
					}
				}
				if f.Maximum != nil {
					if chinese {
						if strings.HasPrefix(f.Type, "*") {
							doc += fmt.Sprintf(" 存在时最大值 %d。", *f.Maximum)
						} else {
							doc += fmt.Sprintf(" 非零最大值 %d。", *f.Maximum)
						}
					} else {
						if strings.HasPrefix(f.Type, "*") {
							doc += fmt.Sprintf(" Present maximum %d.", *f.Maximum)
						} else {
							doc += fmt.Sprintf(" Nonzero maximum %d.", *f.Maximum)
						}
					}
				}
				fmt.Fprintf(b, "| %s | `%s` | `%s` | %s |\n", f.Name, f.Type, f.Wire, strings.ReplaceAll(doc, "|", "\\|"))
			}
			b.WriteString("\n")
		}
	}
	for _, m := range p.Models {
		fmt.Fprintf(b, "### %s\n\n", m.Name)
		doc := m.Doc.English
		if chinese {
			doc = m.Doc.Chinese
		}
		b.WriteString(doc + "\n\n")
		if m.Redact {
			if chinese {
				b.WriteString("默认格式化脱敏；不要记录字段值。\n\n")
			} else {
				b.WriteString("Default formatting is redacted; never log field values.\n\n")
			}
		}
		for _, f := range m.Fields {
			doc := f.Doc.English
			if chinese {
				doc = f.Doc.Chinese
			}
			fmt.Fprintf(b, "- `%s` (`%s`, `%s`): %s\n", f.Name, f.Type, f.Wire, doc)
		}
		b.WriteString("\n")
	}
	if chinese {
		b.WriteString("来源：")
	} else {
		b.WriteString("Sources: ")
	}
	sources := append([]Source(nil), p.Manifest.Sources...)
	sort.Slice(sources, func(i, j int) bool { return sources[i].Operation < sources[j].Operation })
	for i, s := range sources {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "[%s](%s)", s.Operation, s.URL)
	}
	b.WriteString(".\n")
}
