package codegen

import (
	"bytes"
	"context"
	"encoding/json/v2"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestDeterministicRender(t *testing.T) {
	p, err := Load(filepath.Join("..", "..", "metadata", "ecs"))
	if err != nil {
		t.Fatal(err)
	}
	a, err := Render(p)
	if err != nil {
		t.Fatal(err)
	}
	// Reordered source provenance and JSON maps must not influence generated bytes.
	for i, j := 0, len(p.Manifest.Sources)-1; i < j; i, j = i+1, j-1 {
		p.Manifest.Sources[i], p.Manifest.Sources[j] = p.Manifest.Sources[j], p.Manifest.Sources[i]
	}
	b, err := Render(p)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range a {
		if !bytes.Equal(data, b[name]) {
			t.Fatal("nondeterministic output", name)
		}
		if strings.HasSuffix(name, ".go") {
			if _, err := parser.ParseFile(token.NewFileSet(), name, data, parser.AllErrors); err != nil {
				t.Fatal(err)
			}
		}
	}
}

func TestSyntheticGeneratedClient(t *testing.T) {
	if testing.Short() {
		t.Skip("compiler integration")
	}
	dir := t.TempDir()
	rawDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(rawDir, "Lookup.json"), []byte(synthetic), 0600); err != nil {
		t.Fatal(err)
	}
	m := Manifest{SchemaVersion: 1, Product: "Demo", Version: "2026-01-01", Style: "RPC", Package: "demo", Service: "demo"}
	if err := Import(context.Background(), nil, m, []string{"Lookup"}, rawDir, dir); err != nil {
		t.Fatal(err)
	}
	truth := true
	doc := Doc{"Looks up a named value.", "查询具名值。"}
	o := Overlay{SchemaVersion: 1, Doc: doc, Operations: []OperationSpec{{Name: "Lookup", Idempotent: &truth, Inputs: []FieldSpec{{Name: "Name", Wire: "Name", Type: "string", Doc: doc}}, Outputs: []FieldSpec{{Name: "Value", Wire: "Value", Type: "string", Doc: doc}}, Doc: doc, Example: ExampleSpec{Input: map[string]any{"Name": "example"}, Response: `{"Value":"result"}`, Print: "Value", Output: "result"}}}}
	data, err := json.Marshal(o)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "overlay.json"), data, 0600); err != nil {
		t.Fatal(err)
	}
	p, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	files, err := Render(p)
	if err != nil {
		t.Fatal(err)
	}
	compiled := t.TempDir()
	repository, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	// Copy only standard-library runtime source into an isolated module. No network
	// or new public package is needed to compile and execute a new product.
	for _, relative := range []string{".", "credentials", "endpoint", "middleware", "retry", "sdktest", "internal/signing"} {
		entries, err := os.ReadDir(filepath.Join(repository, relative))
		if err != nil {
			t.Fatal(err)
		}
		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
				continue
			}
			data, err := os.ReadFile(filepath.Join(repository, relative, entry.Name()))
			if err != nil {
				t.Fatal(err)
			}
			writeTestFile(t, compiled, filepath.Join(relative, entry.Name()), data)
		}
	}
	writeTestFile(t, compiled, "go.mod", []byte("module "+module+"\n\ngo 1.27.0\n"))
	for name, data := range files {
		writeTestFile(t, compiled, name, data)
	}
	writeTestFile(t, compiled, "services/demo/protocol_test.go", []byte(syntheticProtocolTest))
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "go", "test", "-p", "1", "./services/demo")
	cmd.Dir = compiled
	cmd.Env = append(os.Environ(), "GOPROXY=off", "GOSUMDB=off", "GOWORK=off")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated synthetic service does not run: %v\n%s", err, output)
	}
}

func writeTestFile(t *testing.T, root, name string, data []byte) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data, 0600); err != nil {
		t.Fatal(err)
	}
}

const syntheticProtocolTest = `package demo_test
import("context";"errors";"net/http";"testing";alicloud "github.com/rambow-cloud/alicloud-go-sdk-x";"github.com/rambow-cloud/alicloud-go-sdk-x/credentials";"github.com/rambow-cloud/alicloud-go-sdk-x/sdktest";"github.com/rambow-cloud/alicloud-go-sdk-x/services/demo")
func TestProtocol(t *testing.T){
 provider,_:=credentials.NewStaticProvider(credentials.Credentials{AccessKeyID:"placeholder",AccessKeySecret:"placeholder"})
 tr:=sdktest.NewTransport(sdktest.Step{Body:"{\"Value\":\"result\",\"Unknown\":42}",Check:func(r *http.Request)error{if r.URL.Query().Get("Name")!="a & b"||r.Header.Get("X-Acs-Action")!="Lookup"||r.Header.Get("X-Acs-Version")!="2026-01-01"||r.Header.Get("Authorization")==""{t.Error("incorrect generated wire request")};return nil}})
 c,err:=demo.New(alicloud.Config{Region:"reviewed-region",BaseEndpoint:"https://example.invalid",CredentialsProvider:provider,HTTPClient:&http.Client{Transport:tr}});if err!=nil{t.Fatal(err)}
 var api demo.LookupAPI=c
 _,err=api.Lookup(context.Background(),nil);if err==nil||tr.Calls()!=0{t.Fatal("required input did not fail before transport")}
 out,err:=api.Lookup(context.Background(),&demo.LookupInput{Name:"a & b"});if err!=nil||out.Value!="result"||out.Metadata.Attempts!=1{t.Fatal(out,err)}
 ctx,cancel:=context.WithCancel(context.Background());cancel();_,err=api.Lookup(ctx,nil);if !errors.Is(err,context.Canceled){t.Fatal("lost cancellation",err)}
}
`
