package codegen

import (
	"bytes"
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const productGenerated = "// Code generated by sdkgen product; DO NOT EDIT.\n"
const productMarkdown = "<!-- Code generated by sdkgen product; DO NOT EDIT. -->\n"
const productJSON = "{\n  \"generator\": \"sdkgen product\","

type productType struct {
	Kind     string       `json:"kind"`
	DSLType  string       `json:"dslType"`
	WireType string       `json:"wireType"`
	Ref      string       `json:"ref"`
	Items    *productType `json:"items"`
	Keys     *productType `json:"keys"`
	Values   *productType `json:"values"`
}
type productField struct {
	DSLName       string            `json:"dslName"`
	WireName      string            `json:"wireName"`
	Required      bool              `json:"required"`
	Type          productType       `json:"type"`
	Source        productSource     `json:"source"`
	Documentation []productDocument `json:"documentation"`
	Attributes    struct {
		Deprecated bool `json:"deprecated"`
	} `json:"attributes"`
}
type productDocument struct {
	Attribute string        `json:"attribute"`
	Text      string        `json:"text"`
	Source    productSource `json:"source"`
}
type productModel struct {
	ID              string         `json:"id"`
	Fields          []productField `json:"fields"`
	Extends         *productType   `json:"extends"`
	InheritedFields []productField `json:"inheritedFields"`
	Source          productSource  `json:"source"`
}
type productSource struct {
	File      string `json:"file"`
	Line      int    `json:"line"`
	Column    int    `json:"column"`
	EndLine   int    `json:"endLine"`
	EndColumn int    `json:"endColumn"`
}
type productReason struct {
	Code    string        `json:"code"`
	Message string        `json:"message"`
	Source  productSource `json:"source"`
}
type productCoverageOperation struct {
	Name         string              `json:"name"`
	Status       string              `json:"status"`
	Source       productSource       `json:"source"`
	Reasons      []productReason     `json:"reasons"`
	Capabilities *capabilityCoverage `json:"capabilities,omitempty"`
}
type productOperation struct {
	Name          string            `json:"name"`
	Status        string            `json:"status"`
	Source        productSource     `json:"source"`
	Reasons       []productReason   `json:"reasons"`
	Documentation []productDocument `json:"documentation"`
	Roots         struct {
		Request  productType `json:"request"`
		Response productType `json:"response"`
		Body     productType `json:"body"`
	} `json:"roots"`
	ReachableModels []string     `json:"reachableModels"`
	Protocol        WireProtocol `json:"protocol"`
	Handoff         string       `json:"handoff,omitempty"`
	Bindings        []struct {
		Wire     string `json:"wire"`
		Location string `json:"location"`
		Guard    string `json:"guard"`
		Field    string `json:"field"`
		Encoding string `json:"encoding,omitempty"`
	} `json:"bindings"`
}
type productIR struct {
	Policy        *capabilityPolicy `json:"-"`
	PolicySHA256  string            `json:"-"`
	SchemaVersion int               `json:"schemaVersion"`
	Profile       string            `json:"profile"`
	Product       string            `json:"product"`
	Version       string            `json:"version"`
	Provenance    struct {
		Repository           string `json:"repository"`
		Revision             string `json:"revision"`
		License              string `json:"license"`
		ParserVersion        string `json:"parserVersion"`
		SourceManifestSHA256 string `json:"sourceManifestSHA256"`
	} `json:"provenance"`
	Operations []productOperation `json:"operations"`
	Models     []productModel     `json:"models"`
}
type productPins struct {
	SchemaVersion        int    `json:"schemaVersion"`
	Profile              string `json:"profile"`
	SourceManifestSHA256 string `json:"sourceManifestSHA256"`
	Files                []struct {
		File   string `json:"file"`
		SHA256 string `json:"sha256"`
	} `json:"files"`
}

// GenerateProducts emits all supported full-DSL models and methods without overlays.
// Selected operations assert support; they do not narrow output. Check never writes.
// Invalid sources, selection, rendering or output preflight fail before writes.
func GenerateProducts(ctx context.Context, root string, check bool, selected []string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	if err := safeOutputPath(root, "models/manifest.json"); err != nil {
		return err
	}
	data, err := os.ReadFile(filepath.Join(root, "models", "manifest.json"))
	if err != nil {
		return err
	}
	var pins productPins
	if err := json.Unmarshal(data, &pins); err != nil {
		return err
	}
	if pins.SchemaVersion != 3 || pins.Profile != "rpc-query-json-v1" || len(pins.Files) == 0 {
		return errors.New("product: unsupported IR manifest")
	}
	if err := verifyDSLSource(root, map[string]bool{pins.SourceManifestSHA256: true}); err != nil {
		return err
	}
	var products []productIR
	paths := map[string]bool{}
	for _, pin := range pins.Files {
		if err := ctx.Err(); err != nil {
			return err
		}
		parts := strings.Split(pin.File, "/")
		if len(parts) != 3 || parts[0] != "models" || !packageName.MatchString(parts[1]) || (parts[2] != "ir.json" && parts[2] != "coverage.json") || paths[pin.File] {
			return errors.New("product: invalid or duplicate manifest file")
		}
		paths[pin.File] = true
		if err := safeOutputPath(root, pin.File); err != nil {
			return err
		}
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(pin.File)))
		if err != nil {
			return err
		}
		if digest(content) != pin.SHA256 {
			return fmt.Errorf("product: IR checksum mismatch: %s", pin.File)
		}
		if parts[2] != "ir.json" {
			continue
		}
		var p productIR
		if err := json.Unmarshal(content, &p); err != nil {
			return err
		}
		if p.SchemaVersion != 3 || p.Profile != pins.Profile || p.Product != parts[1] || p.Version == "" || p.Provenance.SourceManifestSHA256 != pins.SourceManifestSHA256 || p.Provenance.Repository != "https://github.com/aliyun/alibabacloud-sdk" || p.Provenance.License != "Apache-2.0" || p.Provenance.ParserVersion != "2.2.1" || len(p.Provenance.Revision) != 40 {
			return errors.New("product: IR provenance mismatch")
		}
		products = append(products, p)
	}
	if len(products) == 0 {
		return errors.New("product: no product IR")
	}
	if err := loadCapabilityPolicies(root, products); err != nil {
		return err
	}
	slices.SortFunc(products, func(a, b productIR) int { return strings.Compare(a.Product, b.Product) })
	operations := map[string]productOperation{}
	for _, p := range products {
		for _, op := range p.Operations {
			key := p.Product + "/" + op.Name
			if _, ok := operations[key]; ok {
				return errors.New("product: duplicate operation")
			}
			operations[key] = op
		}
	}
	for _, name := range selected {
		op, ok := operations[name]
		if !ok {
			return fmt.Errorf("product: unknown selected operation %q", name)
		}
		if op.Status != "lowered" {
			return fmt.Errorf("product: unsupported selected operation %s: %v", name, op.Reasons)
		}
	}
	files := map[string][]byte{}
	for _, p := range products {
		if err := ctx.Err(); err != nil {
			return err
		}
		rendered, err := renderProduct(p)
		if err != nil {
			return fmt.Errorf("product %s: %w", p.Product, err)
		}
		for name, data := range rendered {
			if _, ok := files[name]; ok {
				return errors.New("product: duplicate output")
			}
			files[name] = data
		}
	}
	return reconcileOwned(ctx, root, files, check, []string{"service", "docs/products"}, func(data []byte) bool {
		return bytes.HasPrefix(data, []byte(productGenerated)) || bytes.HasPrefix(data, []byte(productMarkdown)) || bytes.HasPrefix(data, []byte(productJSON))
	})
}
