// Code generated by sdkgen product; DO NOT EDIT.
package ecs_test

import (
	"context"
	"fmt"
	alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"
	"github.com/rambow-cloud/alicloud-go-sdk-x/credentials"
	"github.com/rambow-cloud/alicloud-go-sdk-x/retry"
	"github.com/rambow-cloud/alicloud-go-sdk-x/sdktest"
	"github.com/rambow-cloud/alicloud-go-sdk-x/service/ecs"
	"net/http"
	"time"
)

func capabilityExampleConfig(transport *sdktest.ScriptedTransport) alicloud.Config {
	provider, err := credentials.NewStaticProvider(credentials.Credentials{AccessKeyID: "placeholder", AccessKeySecret: "placeholder"})
	if err != nil {
		panic(err)
	}
	return alicloud.Config{Region: "cn-hangzhou", BaseEndpoint: "https://example.invalid", CredentialsProvider: provider, HTTPClient: &http.Client{Transport: transport}}
}
func ExampleClient_AllocateDedicatedHosts_clientToken() {
	generated := false
	transport := sdktest.NewTransport(sdktest.Step{Body: "{}", Check: func(request *http.Request) error {
		generated = len(request.URL.Query().Get("ClientToken")) == 32
		return nil
	}})
	client, err := ecs.NewFromConfig(capabilityExampleConfig(transport))
	if err != nil {
		panic(err)
	}
	in := &ecs.AllocateDedicatedHostsInput{}
	_, err = client.AllocateDedicatedHosts(context.Background(), in)
	if err != nil {
		panic(err)
	}
	fmt.Println(generated, in.ClientToken == nil)
	// Output: true true
}
func ExampleValidateAllocateDedicatedHostsInput() {
	fmt.Println(ecs.ValidateAllocateDedicatedHostsInput(nil) == nil)
	// Output: true
}
func ExampleDescribeImagesPaginator() {
	transport := sdktest.NewTransport(sdktest.Step{Body: "{\"Images\":{\"Image\":[{}]},\"PageNumber\":1,\"PageSize\":1,\"TotalCount\":2}"}, sdktest.Step{Body: "{\"Images\":{\"Image\":[{}]},\"PageNumber\":2,\"PageSize\":1,\"TotalCount\":2}"})
	client, err := ecs.NewFromConfig(capabilityExampleConfig(transport))
	if err != nil {
		panic(err)
	}
	p, err := ecs.NewDescribeImagesPaginator(client, nil, func(o *ecs.DescribeImagesPaginatorOptions) { o.Limit = 1 })
	if err != nil {
		panic(err)
	}
	pages := 0
	for p.HasMorePages() {
		if _, err := p.NextPage(context.Background()); err != nil {
			panic(err)
		}
		pages++
	}
	fmt.Println(pages)
	// Output: 2
}
func ExampleValidateDescribeImagesInput() {
	fmt.Println(ecs.ValidateDescribeImagesInput(nil) == nil)
	// Output: true
}
func ExampleClient_DescribeImages_retry() {
	transport := sdktest.NewTransport(sdktest.Step{StatusCode: 503, Body: `{"Code":"ServiceUnavailable"}`}, sdktest.Step{Body: "{}"})
	config := capabilityExampleConfig(transport)
	standard, err := retry.NewStandard(retry.Options{})
	if err != nil {
		panic(err)
	}
	config.Retryer = standard
	config.Sleep = func(ctx context.Context, _ time.Duration) error { return ctx.Err() }
	client, err := ecs.NewFromConfig(config)
	if err != nil {
		panic(err)
	}
	out, err := client.DescribeImages(context.Background(), nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(out.Metadata.Attempts)
	// Output: 2
}
func ExampleDescribeInstanceStatusPaginator() {
	transport := sdktest.NewTransport(sdktest.Step{Body: "{\"InstanceStatuses\":{\"InstanceStatus\":[{}]},\"PageNumber\":1,\"PageSize\":1,\"TotalCount\":2}"}, sdktest.Step{Body: "{\"InstanceStatuses\":{\"InstanceStatus\":[{}]},\"PageNumber\":2,\"PageSize\":1,\"TotalCount\":2}"})
	client, err := ecs.NewFromConfig(capabilityExampleConfig(transport))
	if err != nil {
		panic(err)
	}
	p, err := ecs.NewDescribeInstanceStatusPaginator(client, nil, func(o *ecs.DescribeInstanceStatusPaginatorOptions) { o.Limit = 1 })
	if err != nil {
		panic(err)
	}
	pages := 0
	for p.HasMorePages() {
		if _, err := p.NextPage(context.Background()); err != nil {
			panic(err)
		}
		pages++
	}
	fmt.Println(pages)
	// Output: 2
}
func ExampleInstanceRunningWaiter() {
	transport := sdktest.NewTransport(sdktest.Step{Body: "{\"InstanceStatuses\":{\"InstanceStatus\":[{\"InstanceId\":\"i-example\",\"Status\":\"Running\"}]}}"})
	client, err := ecs.NewFromConfig(capabilityExampleConfig(transport))
	if err != nil {
		panic(err)
	}
	w, err := ecs.NewInstanceRunningWaiter(client)
	if err != nil {
		panic(err)
	}
	err = w.Wait(context.Background(), &ecs.DescribeInstanceStatusInput{InstanceIDs: []string{"i-example"}}, time.Second)
	fmt.Println(err == nil)
	// Output: true
}
func ExampleValidateDescribeInstanceStatusInput() {
	fmt.Println(ecs.ValidateDescribeInstanceStatusInput(nil) == nil)
	// Output: true
}
func ExampleClient_DescribeInstanceStatus_retry() {
	transport := sdktest.NewTransport(sdktest.Step{StatusCode: 503, Body: `{"Code":"ServiceUnavailable"}`}, sdktest.Step{Body: "{}"})
	config := capabilityExampleConfig(transport)
	standard, err := retry.NewStandard(retry.Options{})
	if err != nil {
		panic(err)
	}
	config.Retryer = standard
	config.Sleep = func(ctx context.Context, _ time.Duration) error { return ctx.Err() }
	client, err := ecs.NewFromConfig(config)
	if err != nil {
		panic(err)
	}
	out, err := client.DescribeInstanceStatus(context.Background(), nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(out.Metadata.Attempts)
	// Output: 2
}
func ExampleDescribeInstancesPaginator() {
	transport := sdktest.NewTransport(sdktest.Step{Body: "{\"NextToken\":\"next\"}"}, sdktest.Step{Body: "{\"NextToken\":\"\"}"})
	client, err := ecs.NewFromConfig(capabilityExampleConfig(transport))
	if err != nil {
		panic(err)
	}
	p, err := ecs.NewDescribeInstancesPaginator(client, nil, func(o *ecs.DescribeInstancesPaginatorOptions) { o.Limit = 1 })
	if err != nil {
		panic(err)
	}
	pages := 0
	for p.HasMorePages() {
		if _, err := p.NextPage(context.Background()); err != nil {
			panic(err)
		}
		pages++
	}
	fmt.Println(pages)
	// Output: 2
}
func ExampleValidateDescribeInstancesInput() {
	fmt.Println(ecs.ValidateDescribeInstancesInput(nil) == nil)
	// Output: true
}
func ExampleClient_DescribeInstances_retry() {
	transport := sdktest.NewTransport(sdktest.Step{StatusCode: 503, Body: `{"Code":"ServiceUnavailable"}`}, sdktest.Step{Body: "{}"})
	config := capabilityExampleConfig(transport)
	standard, err := retry.NewStandard(retry.Options{})
	if err != nil {
		panic(err)
	}
	config.Retryer = standard
	config.Sleep = func(ctx context.Context, _ time.Duration) error { return ctx.Err() }
	client, err := ecs.NewFromConfig(config)
	if err != nil {
		panic(err)
	}
	out, err := client.DescribeInstances(context.Background(), nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(out.Metadata.Attempts)
	// Output: 2
}
func ExampleClient_DescribeRegions_retry() {
	transport := sdktest.NewTransport(sdktest.Step{StatusCode: 503, Body: `{"Code":"ServiceUnavailable"}`}, sdktest.Step{Body: "{}"})
	config := capabilityExampleConfig(transport)
	standard, err := retry.NewStandard(retry.Options{})
	if err != nil {
		panic(err)
	}
	config.Retryer = standard
	config.Sleep = func(ctx context.Context, _ time.Duration) error { return ctx.Err() }
	client, err := ecs.NewFromConfig(config)
	if err != nil {
		panic(err)
	}
	out, err := client.DescribeRegions(context.Background(), nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(out.Metadata.Attempts)
	// Output: 2
}
