// Code generated by sdkgen product; DO NOT EDIT.

// Package ecs provides complete models and methods for 283 supported native RPC actions.
// Construct with NewFromConfig. Clients are safe for concurrent use; inputs must not
// be mutated during calls. Nil optional pointers omit members; explicit zeros survive.
// Output preserves the JSON body containers and adds transport Metadata.
// Unsupported DSL actions are listed in docs/products/ecs.coverage.json.
// Reviewed native adapters and operation policies are listed in the product guide.
// See docs/products/ecs.md for bilingual usage, coverage and migration guidance.
// Models and service descriptions derive from pinned Apache-2.0 Alibaba Cloud DSL.
// Package LICENSE and NOTICE preserve terms and attribution; see documentation coverage.
// Service prose is informational and does not create SDK validation. No Tea runtime is required.
package ecs
