// Code generated by sdkgen product; DO NOT EDIT.

// Package ecs provides complete models and methods for 283 supported native RPC actions.
// Construct with NewFromConfig. Clients are safe for concurrent use; inputs must not
// be mutated during calls. Nil optional pointers omit members; explicit zeros survive.
// Output preserves the JSON body containers and adds transport Metadata.
// Unsupported DSL actions are listed in docs/products/ecs.coverage.json.
// This package does not yet generate paginator/waiter policies; see issue #37.
// See docs/products/ecs.md for bilingual usage, coverage and migration guidance.
// Models derive from pinned Apache-2.0 Alibaba Cloud DSL; upstream notices remain
// under sources/darabonba/licenses. No Tea runtime dependency is required.
package ecs
