// Code generated by sdkgen product; DO NOT EDIT.
package ecs

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/internal/rpcmodel"
	"github.com/rambow-cloud/alicloud-go-sdk-x/pagination"
	"strconv"
)

// DescribeAutoSnapshotPolicyExPaginatorOptions controls native pagination and copied operation options.
type DescribeAutoSnapshotPolicyExPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeAutoSnapshotPolicyExPaginator is a single-consumer iterator; do not copy or share it.
type DescribeAutoSnapshotPolicyExPaginator struct {
	engine         *pagination.Paginator[*DescribeAutoSnapshotPolicyExOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeAutoSnapshotPolicyExPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeAutoSnapshotPolicyExPaginator(api DescribeAutoSnapshotPolicyExAPI, input *DescribeAutoSnapshotPolicyExInput, optFns ...func(*DescribeAutoSnapshotPolicyExPaginatorOptions)) (*DescribeAutoSnapshotPolicyExPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeAutoSnapshotPolicyExPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeAutoSnapshotPolicyExInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 100 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeAutoSnapshotPolicyExPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeAutoSnapshotPolicyExOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeAutoSnapshotPolicyEx(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 100 {
				return pagination.Page[*DescribeAutoSnapshotPolicyExOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.AutoSnapshotPolicies != nil {
				count = len(out.AutoSnapshotPolicies.AutoSnapshotPolicy)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeAutoSnapshotPolicyExPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeAutoSnapshotPolicyExPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeAutoSnapshotPolicyExOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeCommandsPaginatorOptions controls native pagination and copied operation options.
type DescribeCommandsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeCommandsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeCommandsPaginator struct {
	engine         *pagination.Paginator[*DescribeCommandsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeCommandsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeCommandsPaginator(api DescribeCommandsAPI, input *DescribeCommandsInput, optFns ...func(*DescribeCommandsPaginatorOptions)) (*DescribeCommandsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeCommandsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if in.PageNumber != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if in.PageSize != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if err := ValidateDescribeCommandsInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 50 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeCommandsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeCommandsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeCommandsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeCommands(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeCommandsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeCommandsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeCommandsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeCommandsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeCommandsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeCommandsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeDeploymentSetsPaginatorOptions controls native pagination and copied operation options.
type DescribeDeploymentSetsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeDeploymentSetsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeDeploymentSetsPaginator struct {
	engine         *pagination.Paginator[*DescribeDeploymentSetsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeDeploymentSetsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeDeploymentSetsPaginator(api DescribeDeploymentSetsAPI, input *DescribeDeploymentSetsInput, optFns ...func(*DescribeDeploymentSetsPaginatorOptions)) (*DescribeDeploymentSetsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeDeploymentSetsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeDeploymentSetsInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeDeploymentSetsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeDeploymentSetsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeDeploymentSetsOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeDeploymentSets(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeDeploymentSetsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeDeploymentSetsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeDeploymentSetsOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeDeploymentSetsOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeDeploymentSetsOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeDeploymentSetsOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeDeploymentSetsOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeDeploymentSetsOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.DeploymentSets != nil {
				count = len(out.DeploymentSets.DeploymentSet)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeDeploymentSetsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeDeploymentSetsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeDeploymentSetsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeDisksPaginatorOptions controls native pagination and copied operation options.
type DescribeDisksPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeDisksPaginator is a single-consumer iterator; do not copy or share it.
type DescribeDisksPaginator struct {
	engine         *pagination.Paginator[*DescribeDisksOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeDisksPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeDisksPaginator(api DescribeDisksAPI, input *DescribeDisksInput, optFns ...func(*DescribeDisksPaginatorOptions)) (*DescribeDisksPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeDisksPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 500 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if in.PageNumber != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if in.PageSize != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if err := ValidateDescribeDisksInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 500 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeDisksPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeDisksOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeDisksOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeDisks(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeDisksOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeDisksOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeDisksOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeDisksPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeDisksPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeDisksOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeImagesPaginatorOptions controls native pagination and copied operation options.
type DescribeImagesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeImagesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeImagesPaginator struct {
	engine         *pagination.Paginator[*DescribeImagesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeImagesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeImagesPaginator(api DescribeImagesAPI, input *DescribeImagesInput, optFns ...func(*DescribeImagesPaginatorOptions)) (*DescribeImagesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeImagesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeImagesInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 100 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeImagesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeImagesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeImagesOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeImages(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeImagesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeImagesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeImagesOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeImagesOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeImagesOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeImagesOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeImagesOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 100 {
				return pagination.Page[*DescribeImagesOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.Images != nil {
				count = len(out.Images.Image)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeImagesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeImagesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeImagesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeInstanceAutoRenewAttributePaginatorOptions controls native pagination and copied operation options.
type DescribeInstanceAutoRenewAttributePaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeInstanceAutoRenewAttributePaginator is a single-consumer iterator; do not copy or share it.
type DescribeInstanceAutoRenewAttributePaginator struct {
	engine         *pagination.Paginator[*DescribeInstanceAutoRenewAttributeOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInstanceAutoRenewAttributePaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeInstanceAutoRenewAttributePaginator(api DescribeInstanceAutoRenewAttributeAPI, input *DescribeInstanceAutoRenewAttributeInput, optFns ...func(*DescribeInstanceAutoRenewAttributePaginatorOptions)) (*DescribeInstanceAutoRenewAttributePaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInstanceAutoRenewAttributePaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(strconv.FormatInt(int64(1), 10))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(strconv.FormatInt(int64(10), 10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(strconv.FormatInt(int64(options.Limit), 10))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(^uint(0)>>1) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 100 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeInstanceAutoRenewAttributePaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstanceAutoRenewAttributeOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(strconv.FormatInt(int64(cursor.PageNumber), 10))
		}

		out, err := api.DescribeInstanceAutoRenewAttribute(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 100 {
				return pagination.Page[*DescribeInstanceAutoRenewAttributeOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.InstanceRenewAttributes != nil {
				count = len(out.InstanceRenewAttributes.InstanceRenewAttribute)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(^uint(0)>>1) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeInstanceAutoRenewAttributePaginator) HasMorePages() bool {
	return p.engine.HasMorePages()
}

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeInstanceAutoRenewAttributePaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInstanceAutoRenewAttributeOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeInstanceMaintenanceAttributesPaginatorOptions controls native pagination and copied operation options.
type DescribeInstanceMaintenanceAttributesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeInstanceMaintenanceAttributesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeInstanceMaintenanceAttributesPaginator struct {
	engine         *pagination.Paginator[*DescribeInstanceMaintenanceAttributesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInstanceMaintenanceAttributesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeInstanceMaintenanceAttributesPaginator(api DescribeInstanceMaintenanceAttributesAPI, input *DescribeInstanceMaintenanceAttributesInput, optFns ...func(*DescribeInstanceMaintenanceAttributesPaginatorOptions)) (*DescribeInstanceMaintenanceAttributesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInstanceMaintenanceAttributesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeInstanceMaintenanceAttributesInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int64(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int64(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int64(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(^uint(0)>>1) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 100 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeInstanceMaintenanceAttributesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstanceMaintenanceAttributesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int64(cursor.PageNumber))
		}

		out, err := api.DescribeInstanceMaintenanceAttributes(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 100 {
				return pagination.Page[*DescribeInstanceMaintenanceAttributesOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.MaintenanceAttributes != nil {
				count = len(out.MaintenanceAttributes.MaintenanceAttribute)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(^uint(0)>>1) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeInstanceMaintenanceAttributesPaginator) HasMorePages() bool {
	return p.engine.HasMorePages()
}

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeInstanceMaintenanceAttributesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInstanceMaintenanceAttributesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeInstanceStatusPaginatorOptions controls native pagination and copied operation options.
type DescribeInstanceStatusPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeInstanceStatusPaginator is a single-consumer iterator; do not copy or share it.
type DescribeInstanceStatusPaginator struct {
	engine         *pagination.Paginator[*DescribeInstanceStatusOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInstanceStatusPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeInstanceStatusPaginator(api DescribeInstanceStatusAPI, input *DescribeInstanceStatusInput, optFns ...func(*DescribeInstanceStatusPaginatorOptions)) (*DescribeInstanceStatusPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInstanceStatusPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeInstanceStatusInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(50))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeInstanceStatusPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstanceStatusOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeInstanceStatusOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeInstanceStatus(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeInstanceStatusOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstanceStatusOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.InstanceStatuses != nil {
				count = len(out.InstanceStatuses.InstanceStatus)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeInstanceStatusPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeInstanceStatusPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInstanceStatusOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeInstancesPaginatorOptions controls native pagination and copied operation options.
type DescribeInstancesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeInstancesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeInstancesPaginator struct {
	engine         *pagination.Paginator[*DescribeInstancesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInstancesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeInstancesPaginator(api DescribeInstancesAPI, input *DescribeInstancesInput, optFns ...func(*DescribeInstancesPaginatorOptions)) (*DescribeInstancesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInstancesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeInstancesInput(in); err != nil {
		return nil, err
	}
	pageMode := (in.PageNumber != nil) || (in.PageSize != nil)
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 100 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}
	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeInstancesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstancesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeInstancesOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}
		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeInstances(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeInstancesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstancesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstancesOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}
		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeInstancesOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeInstancesOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeInstancesOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeInstancesOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 100 {
				return pagination.Page[*DescribeInstancesOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.Instances != nil {
				count = len(out.Instances.Instance)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeInstancesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeInstancesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInstancesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeInvocationsPaginatorOptions controls native pagination and copied operation options.
type DescribeInvocationsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeInvocationsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeInvocationsPaginator struct {
	engine         *pagination.Paginator[*DescribeInvocationsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInvocationsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeInvocationsPaginator(api DescribeInvocationsAPI, input *DescribeInvocationsInput, optFns ...func(*DescribeInvocationsPaginatorOptions)) (*DescribeInvocationsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInvocationsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if in.PageNumber != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if in.PageSize != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if err := ValidateDescribeInvocationsInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 50 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeInvocationsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInvocationsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeInvocationsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeInvocations(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeInvocationsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInvocationsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInvocationsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeInvocationsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeInvocationsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInvocationsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeKeyPairsPaginatorOptions controls native pagination and copied operation options.
type DescribeKeyPairsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeKeyPairsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeKeyPairsPaginator struct {
	engine         *pagination.Paginator[*DescribeKeyPairsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeKeyPairsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeKeyPairsPaginator(api DescribeKeyPairsAPI, input *DescribeKeyPairsInput, optFns ...func(*DescribeKeyPairsPaginatorOptions)) (*DescribeKeyPairsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeKeyPairsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeKeyPairsInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeKeyPairsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeKeyPairsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeKeyPairsOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeKeyPairs(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeKeyPairsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeKeyPairsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeKeyPairsOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeKeyPairsOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeKeyPairsOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeKeyPairsOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeKeyPairsOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeKeyPairsOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.KeyPairs != nil {
				count = len(out.KeyPairs.KeyPair)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeKeyPairsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeKeyPairsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeKeyPairsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeNetworkInterfacesPaginatorOptions controls native pagination and copied operation options.
type DescribeNetworkInterfacesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeNetworkInterfacesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeNetworkInterfacesPaginator struct {
	engine         *pagination.Paginator[*DescribeNetworkInterfacesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeNetworkInterfacesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeNetworkInterfacesPaginator(api DescribeNetworkInterfacesAPI, input *DescribeNetworkInterfacesInput, optFns ...func(*DescribeNetworkInterfacesPaginatorOptions)) (*DescribeNetworkInterfacesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeNetworkInterfacesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 500 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if in.PageNumber != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if in.PageSize != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if err := ValidateDescribeNetworkInterfacesInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 500 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeNetworkInterfacesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeNetworkInterfacesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeNetworkInterfacesOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeNetworkInterfaces(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeNetworkInterfacesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeNetworkInterfacesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeNetworkInterfacesOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeNetworkInterfacesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeNetworkInterfacesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeNetworkInterfacesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeSecurityGroupsPaginatorOptions controls native pagination and copied operation options.
type DescribeSecurityGroupsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeSecurityGroupsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeSecurityGroupsPaginator struct {
	engine         *pagination.Paginator[*DescribeSecurityGroupsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeSecurityGroupsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeSecurityGroupsPaginator(api DescribeSecurityGroupsAPI, input *DescribeSecurityGroupsInput, optFns ...func(*DescribeSecurityGroupsPaginatorOptions)) (*DescribeSecurityGroupsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeSecurityGroupsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if in.PageNumber != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if in.PageSize != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if err := ValidateDescribeSecurityGroupsInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeSecurityGroupsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeSecurityGroupsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeSecurityGroupsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeSecurityGroups(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeSecurityGroupsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeSecurityGroupsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeSecurityGroupsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeSecurityGroupsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeSecurityGroupsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeSecurityGroupsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeSnapshotsPaginatorOptions controls native pagination and copied operation options.
type DescribeSnapshotsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeSnapshotsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeSnapshotsPaginator struct {
	engine         *pagination.Paginator[*DescribeSnapshotsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeSnapshotsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeSnapshotsPaginator(api DescribeSnapshotsAPI, input *DescribeSnapshotsInput, optFns ...func(*DescribeSnapshotsPaginatorOptions)) (*DescribeSnapshotsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeSnapshotsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if in.PageNumber != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if in.PageSize != nil {
		return nil, errors.New("token paginator does not accept legacy page fields")
	}
	if err := ValidateDescribeSnapshotsInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeSnapshotsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeSnapshotsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeSnapshotsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeSnapshots(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeSnapshotsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeSnapshotsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeSnapshotsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeSnapshotsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeSnapshotsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeSnapshotsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}
