// Code generated by sdkgen product; DO NOT EDIT.
package ecs

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/internal/rpcmodel"
)

// ValidateAllocateDedicatedHostsInput checks only the reviewed sparse constraints without changing input.
// Nil is an empty request; diagnostics identify rules without including values.
func ValidateAllocateDedicatedHostsInput(in *AllocateDedicatedHostsInput) error {
	if in == nil {
		return nil
	}
	if in.ClientToken != nil {
		if len(*in.ClientToken) < 1 {
			return errors.New("invalid ClientToken: shorter than minimum")
		}
		if len(*in.ClientToken) > 64 {
			return errors.New("invalid ClientToken: longer than maximum")
		}
		for _, value := range []byte(*in.ClientToken) {
			if value > 127 {
				return errors.New("invalid ClientToken: ASCII required")
			}
		}
	}
	return nil
}
func prepareAllocateDedicatedHostsInput(ctx context.Context, in *AllocateDedicatedHostsInput) error {
	if in.ClientToken == nil {
		token, err := rpcmodel.NewClientToken(ctx)
		if err != nil {
			return err
		}
		in.ClientToken = token
	}
	return nil
}

// ValidateDescribeImagesInput checks only the reviewed sparse constraints without changing input.
// Nil is an empty request; diagnostics identify rules without including values.
func ValidateDescribeImagesInput(in *DescribeImagesInput) error {
	if in == nil {
		return nil
	}
	if in.PageNumber != nil {
		if *in.PageNumber < 1 {
			return errors.New("invalid PageNumber: below minimum")
		}
	}
	if in.PageSize != nil {
		if *in.PageSize < 1 {
			return errors.New("invalid PageSize: below minimum")
		}
		if *in.PageSize > 100 {
			return errors.New("invalid PageSize: above maximum")
		}
	}
	return nil
}

// ValidateDescribeInstanceStatusInput checks only the reviewed sparse constraints without changing input.
// Nil is an empty request; diagnostics identify rules without including values.
func ValidateDescribeInstanceStatusInput(in *DescribeInstanceStatusInput) error {
	if in == nil {
		return nil
	}
	if in.PageNumber != nil {
		if *in.PageNumber < 1 {
			return errors.New("invalid PageNumber: below minimum")
		}
	}
	if in.PageSize != nil {
		if *in.PageSize < 1 {
			return errors.New("invalid PageSize: below minimum")
		}
		if *in.PageSize > 50 {
			return errors.New("invalid PageSize: above maximum")
		}
	}
	if true {
		if len(in.InstanceIDs) > 100 {
			return errors.New("invalid InstanceId: too many items")
		}
		for _, value := range in.InstanceIDs {
			if value == "" {
				return errors.New("invalid InstanceId: empty item")
			}
		}
	}
	return nil
}

// ValidateDescribeInstancesInput checks only the reviewed sparse constraints without changing input.
// Nil is an empty request; diagnostics identify rules without including values.
func ValidateDescribeInstancesInput(in *DescribeInstancesInput) error {
	if in == nil {
		return nil
	}
	if in.PageNumber != nil {
		if *in.PageNumber < 1 {
			return errors.New("invalid PageNumber: below minimum")
		}
	}
	if in.PageSize != nil {
		if *in.PageSize < 1 {
			return errors.New("invalid PageSize: below minimum")
		}
		if *in.PageSize > 100 {
			return errors.New("invalid PageSize: above maximum")
		}
	}
	if in.MaxResults != nil {
		if *in.MaxResults < 1 {
			return errors.New("invalid MaxResults: below minimum")
		}
		if *in.MaxResults > 100 {
			return errors.New("invalid MaxResults: above maximum")
		}
	}
	if (in.NextToken != nil || in.MaxResults != nil) && (in.PageNumber != nil || in.PageSize != nil) {
		return errors.New("token and page-number parameters cannot be combined")
	}
	return nil
}
