// Code generated by sdkgen product; DO NOT EDIT.

// Package fc provides complete models and methods for 73 supported native ROA actions.
// Construct with NewFromConfig. Clients are safe for concurrent use; inputs must not
// be mutated during calls. Nil optional pointers omit members; explicit zeros survive.
// JSON outputs preserve body containers and add transport Metadata. Binary outputs
// return owned io.ReadCloser bodies: close them after use. Timeout and context
// cover reads; byte limits apply and late read failures never retry.
// Unsupported DSL actions are listed in docs/products/fc.coverage.json.
// Reviewed native adapters and operation policies are listed in the product guide.
// See docs/products/fc.md for bilingual usage, coverage and migration guidance.
// Models and service descriptions derive from pinned Apache-2.0 Alibaba Cloud DSL.
// Package LICENSE and NOTICE preserve terms and attribution; see documentation coverage.
// Service prose is informational and does not create SDK validation. No Tea runtime is required.
package fc
