// Code generated by sdkgen; DO NOT EDIT.

// Package sts provides selected STS RPC operations generated from pinned metadata. Clients are concurrency safe; inputs are copied. Shared runtime errors and cancellation preserve their identity. Coverage is limited to the listed operations and fields.
package sts
