// Code generated by sdkgen; DO NOT EDIT.
package sts

import (
	"context"
	"errors"
	alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"
	"net/url"
	"strconv"
	"time"
)

// Options aliases shared per-call runtime options.
type Options = alicloud.CallOptions

// Client is a concurrency-safe Sts client. Construct it with New.
type Client struct{ runtime *alicloud.Client }

// New validates and copies runtime configuration. Custom extension objects must be concurrency safe.
func New(config alicloud.Config) (*Client, error) {
	c, err := alicloud.NewClient(config)
	if err != nil {
		return nil, err
	}
	return &Client{runtime: c}, nil
}

// AssumedRoleUser contains selected response properties.
type AssumedRoleUser struct {
	// ARN contains selected wire field Arn.
	ARN string `json:"Arn"`
	// AssumedRoleID contains selected wire field AssumedRoleId.
	AssumedRoleID string `json:"AssumedRoleId"`
}

// RoleCredentials contains selected response properties.
type RoleCredentials struct {
	// AccessKeyID contains the temporary access key identifier.
	AccessKeyID string `json:"AccessKeyId"`
	// AccessKeySecret contains the temporary signing secret; it must never be logged.
	AccessKeySecret string `json:"AccessKeySecret"`
	// SecurityToken contains the STS security token; no fixed maximum length is assumed.
	SecurityToken string `json:"SecurityToken"`
	// ExpiresAt contains the parsed RFC3339 service expiration.
	ExpiresAt time.Time `json:"Expiration"`
}

// String returns a redacted representation.
func (RoleCredentials) String() string { return "RoleCredentials(<redacted>)" }

// GoString returns a redacted representation for Go formatting.
func (c RoleCredentials) GoString() string { return c.String() }

// AssumeRoleInput contains the selected query parameters; zero optional values are omitted.
type AssumeRoleInput struct {
	// RoleARN specifies the required RAM role ARN, for example acs:ram::123456789012:role/example.
	// This field is required.
	RoleARN string
	// RoleSessionName specifies a required audit session name of 2..64 ASCII characters.
	// This field is required.
	RoleSessionName string
	// DurationSeconds specifies the token lifetime; zero omits it (service default 3600), nonzero must be at least 900. The role maximum is a service decision.
	DurationSeconds int64
	// Policy specifies an optional restrictive JSON object policy limited to 2048 bytes; empty omits it.
	Policy string
	// ExternalID specifies an optional external identity of 2..1224 ASCII characters; empty omits it.
	ExternalID string
	// SourceIdentity contains the source identity retained through role chaining; empty input omits it, otherwise 2..64 ASCII characters and no reserved prefix are accepted.
	SourceIdentity string
}

// AssumeRoleOutput contains selected response fields and transport metadata.
type AssumeRoleOutput struct {
	// Credentials contains selected wire field Credentials.
	Credentials RoleCredentials `json:"Credentials"`
	// AssumedRoleUser contains selected wire field AssumedRoleUser.
	AssumedRoleUser AssumedRoleUser `json:"AssumedRoleUser"`
	// SourceIdentity contains the source identity retained through role chaining; empty input omits it, otherwise 2..64 ASCII characters and no reserved prefix are accepted.
	SourceIdentity string `json:"SourceIdentity"`
	// Metadata contains request ID, status and attempt count; it is excluded from wire decoding.
	Metadata alicloud.Metadata `json:"-"`
}

// AssumeRoleAPI is the minimal operation interface for consumers and fakes.
type AssumeRoleAPI interface {
	// AssumeRole executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
	AssumeRole(context.Context, *AssumeRoleInput, ...func(*Options)) (*AssumeRoleOutput, error)
}

// AssumeRole executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
// API version 2015-04-01. Errors preserve cancellation and structured service causes.
// This operation is conservatively non-idempotent and is not retried by Standard.
func (c *Client) AssumeRole(ctx context.Context, input *AssumeRoleInput, opts ...func(*Options)) (*AssumeRoleOutput, error) {
	fail := func(err error) (*AssumeRoleOutput, error) { return nil, generatedValidation(ctx, "AssumeRole", err) }
	if err := ctx.Err(); err != nil {
		return fail(err)
	}
	if input == nil {
		return fail(errors.New("input required"))
	}
	var in AssumeRoleInput
	if input != nil {
		in = *input
	}
	if err := validateAssumeRole(in); err != nil {
		return fail(err)
	}
	region := ""
	q := url.Values{}
	if in.RoleARN == "" {
		return fail(errors.New("required parameter RoleArn"))
	}
	if in.RoleARN != "" {
		q.Set("RoleArn", in.RoleARN)
	}
	if in.RoleSessionName == "" {
		return fail(errors.New("required parameter RoleSessionName"))
	}
	if in.RoleSessionName != "" {
		q.Set("RoleSessionName", in.RoleSessionName)
	}
	if in.DurationSeconds != 0 {
		q.Set("DurationSeconds", strconv.FormatInt(in.DurationSeconds, 10))
	}
	if in.Policy != "" {
		q.Set("Policy", in.Policy)
	}
	if in.ExternalID != "" {
		q.Set("ExternalId", in.ExternalID)
	}
	if in.SourceIdentity != "" {
		q.Set("SourceIdentity", in.SourceIdentity)
	}
	var wire struct {
		W0 AssumedRoleUser `json:"AssumedRoleUser"`
		W1 RoleCredentials `json:"Credentials"`
		W2 string          `json:"SourceIdentity"`
	}
	meta, err := c.runtime.Invoke(ctx, alicloud.Operation{Service: "sts", Name: "AssumeRole", Version: "2015-04-01", Idempotent: false}, alicloud.Request{Method: "POST", Path: "/", Region: region, Query: q, Header: map[string][]string{"Content-Type": {"application/x-www-form-urlencoded"}}}, &wire, opts...)
	if err != nil {
		return nil, err
	}
	return &AssumeRoleOutput{Metadata: meta, Credentials: wire.W1, AssumedRoleUser: wire.W0, SourceIdentity: wire.W2}, nil
}
func generatedValidation(ctx context.Context, name string, err error) error {
	if ctx.Err() != nil {
		err = ctx.Err()
	}
	return &alicloud.OperationError{Service: "sts", Operation: name, Err: err}
}
