// Code generated by sdkgen; DO NOT EDIT.
package ecs

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/pagination"
	"github.com/rambow-cloud/alicloud-go-sdk-x/waiter"
	"time"
)

// DescribeInstancesPaginator adapts the shared engine with reviewed token/page policies.
// It defaults to token mode; explicit page or size selects legacy mode. Use one consumer.
type DescribeInstancesPaginator struct {
	engine *pagination.Paginator[*DescribeInstancesOutput]
}

// NewDescribeInstancesPaginator copies input/options and starts at the supplied cursor.
// Nil input selects token mode with the reviewed default result count.
func NewDescribeInstancesPaginator(api DescribeInstancesAPI, input *DescribeInstancesInput, opts ...func(*Options)) (*DescribeInstancesPaginator, error) {
	if api == nil {
		return nil, errors.New("nil paginator API")
	}
	var in DescribeInstancesInput
	if input != nil {
		in = *input
		in.InstanceIDs = append([]string(nil), input.InstanceIDs...)
	}
	if err := validateInstances(in); err != nil {
		return nil, err
	}
	copiedOptions := append([]func(*Options){}, opts...)
	pageMode := in.PageNumber != 0 || in.PageSize != 0
	initial := pagination.Cursor{Token: in.NextToken}
	if pageMode {
		if in.PageNumber == 0 {
			in.PageNumber = 1
		}
		if in.PageSize == 0 {
			in.PageSize = 10
		}
		initial = pagination.Cursor{PageNumber: in.PageNumber}
	} else {
		if in.MaxResults == 0 {
			in.MaxResults = 10
		}
	}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstancesOutput], error) {
		request := in
		request.InstanceIDs = append([]string(nil), in.InstanceIDs...)

		if pageMode {
			request.PageNumber = cursor.PageNumber
		} else {
			request.NextToken = cursor.Token
		}
		out, err := api.DescribeInstances(ctx, &request, copiedOptions...)
		if err != nil {
			return pagination.Page[*DescribeInstancesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstancesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstancesOutput]{Value: out, Next: pagination.Cursor{Token: out.NextToken}, HasMore: out.NextToken != ""}
		if pageMode {
			if out.TotalCount < 0 || (out.PageNumber != 0 && out.PageNumber != cursor.PageNumber) {
				return pagination.Page[*DescribeInstancesOutput]{}, errors.New("inconsistent pagination metadata")
			}
			size := out.PageSize
			if size <= 0 {
				size = in.PageSize
			}
			page.Next = pagination.Cursor{PageNumber: cursor.PageNumber + 1}
			page.HasMore = len(out.Instances) > 0 && int64(cursor.PageNumber)*int64(size) < int64(out.TotalCount)
		}
		return page, nil
	})
	if err != nil {
		return nil, err
	}
	return &DescribeInstancesPaginator{engine: engine}, nil
}

// HasMorePages reports whether another service page is available.
func (p *DescribeInstancesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches without changing the original input; errors do not advance.
func (p *DescribeInstancesPaginator) NextPage(ctx context.Context) (*DescribeInstancesOutput, error) {
	return p.engine.NextPage(ctx)
}

// InstanceRunningWaiter waits until all explicitly requested identities have the reviewed success state.
// Missing identities and reviewed retry states continue; unknown or duplicate states fail.
type InstanceRunningWaiter struct {
	engine *waiter.Waiter[*DescribeInstanceStatusOutput]
}

// NewInstanceRunningWaiter copies input/options and polls one bounded first page.
// All IDs must be nonempty and distinct; operation errors fail immediately.
func NewInstanceRunningWaiter(api DescribeInstanceStatusAPI, input *DescribeInstanceStatusInput, options waiter.Options, opts ...func(*Options)) (*InstanceRunningWaiter, error) {
	if api == nil || input == nil || len(input.InstanceIDs) == 0 || len(input.InstanceIDs) > 50 || input.PageNumber > 1 || input.PageNumber < 0 {
		return nil, errors.New("waiter requires a bounded distinct ID list on the first page")
	}
	in := *input
	in.InstanceIDs = append([]string(nil), input.InstanceIDs...)

	in.PageNumber = 1
	in.PageSize = 50
	copiedOptions := append([]func(*Options){}, opts...)
	required := map[string]bool{}
	for _, id := range in.InstanceIDs {
		if id == "" || required[id] {
			return nil, errors.New("invalid waiter IDs")
		}
		required[id] = true
	}
	engine, err := waiter.New(func(ctx context.Context) (*DescribeInstanceStatusOutput, error) {
		request := in
		request.InstanceIDs = append([]string(nil), in.InstanceIDs...)
		return api.DescribeInstanceStatus(ctx, &request, copiedOptions...)
	}, func(out *DescribeInstanceStatusOutput, err error) waiter.Decision {
		if err != nil || out == nil {
			return waiter.Failure
		}
		states := map[string]string{}
		for _, entry := range out.InstanceStatuses {
			if !required[entry.InstanceID] {
				continue
			}
			if _, ok := states[entry.InstanceID]; ok {
				return waiter.Failure
			}
			states[entry.InstanceID] = entry.Status
		}
		success := 0
		for id := range required {
			state, present := states[id]
			if !present {
				continue
			}
			switch state {
			case "Running":
				success++
			case "Pending", "Starting", "Stopping", "Stopped":
			default:
				return waiter.Failure
			}
		}
		if success == len(required) {
			return waiter.Success
		}
		return waiter.Retry
	}, options)
	if err != nil {
		return nil, err
	}
	return &InstanceRunningWaiter{engine: engine}, nil
}

// Wait requires a positive total duration; caller context bounds each operation.
// Waiter expiry preserves waiter.ErrTimeout independently of operation retry timeouts.
func (w *InstanceRunningWaiter) Wait(ctx context.Context, maxWait time.Duration) (*DescribeInstanceStatusOutput, error) {
	return w.engine.Wait(ctx, maxWait)
}
