// Code generated by sdkgen; DO NOT EDIT.
package ecs

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/pagination"
	"github.com/rambow-cloud/alicloud-go-sdk-x/waiter"
	"time"
)

// DescribeInstancesPaginatorOptions controls page size and continuation protection.
// Constructor defaults stop duplicate tokens; callbacks must not retain options.
type DescribeInstancesPaginatorOptions struct {
	// Limit overrides the native page size when positive; zero preserves input/default.
	Limit int
	// StopOnDuplicateToken stops after returning a page with an already seen cursor.
	// Defaults to true. Explicit false may allow unbounded cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies service options to every fetch; NextPage options run last.
	ClientOptions []func(*Options)
}

// DescribeInstancesPaginator traverses reviewed native pagination with one consumer.
// Input pointers/slices and option registrations are copied; do not share or copy it.
type DescribeInstancesPaginator struct {
	engine         *pagination.Paginator[*DescribeInstancesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInstancesPaginator copies input and applies dedicated paginator options.
// Zero size uses the reviewed default; errors/cancellation do not advance the cursor.
func NewDescribeInstancesPaginator(api DescribeInstancesAPI, input *DescribeInstancesInput, optFns ...func(*DescribeInstancesPaginatorOptions)) (*DescribeInstancesPaginator, error) {
	if api == nil {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInstancesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 {
		return nil, errors.New("negative paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	var in DescribeInstancesInput
	if input != nil {
		in = *input
		in.InstanceIDs = append([]string(nil), input.InstanceIDs...)
	}
	pageMode := in.PageNumber != 0 || in.PageSize != 0
	initial := pagination.Cursor{}

	if pageMode {
		if in.PageNumber < 0 || in.PageSize < 0 {
			return nil, errors.New("negative page parameters")
		}
		if in.PageNumber == 0 {
			in.PageNumber = 1
		}
		if in.PageSize == 0 {
			in.PageSize = 10
		}
		if options.Limit > 0 {
			in.PageSize = options.Limit
		}
		if in.PageNumber < 1 {
			return nil, errors.New("paginator parameter below minimum")
		}
		if in.PageSize < 1 {
			return nil, errors.New("paginator parameter below minimum")
		}
		if in.PageSize > 100 {
			return nil, errors.New("paginator parameter above maximum")
		}
		initial = pagination.Cursor{PageNumber: in.PageNumber}
	}

	if !pageMode {
		if in.MaxResults < 0 {
			return nil, errors.New("negative token limit")
		}
		if in.MaxResults == 0 {
			in.MaxResults = 10
		}
		if options.Limit > 0 {
			in.MaxResults = options.Limit
		}
		if in.MaxResults < 1 {
			return nil, errors.New("paginator parameter below minimum")
		}
		if in.MaxResults > 100 {
			return nil, errors.New("paginator parameter above maximum")
		}
		initial = pagination.Cursor{Token: in.NextToken}
	}

	if err := validateInstances(in); err != nil {
		return nil, err
	}
	p := &DescribeInstancesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstancesOutput], error) {
		request := in
		request.InstanceIDs = append([]string(nil), in.InstanceIDs...)

		if pageMode {
			request.PageNumber = cursor.PageNumber
		}
		if !pageMode {
			request.NextToken = cursor.Token
		}
		out, err := api.DescribeInstances(ctx, &request, p.pendingOptions...)
		if err != nil {
			return pagination.Page[*DescribeInstancesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstancesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstancesOutput]{Value: out}
		if !pageMode {
			page.Next = pagination.Cursor{Token: out.NextToken}
			page.HasMore = out.NextToken != ""
		}

		if pageMode {
			if out.TotalCount < 0 || out.PageSize < 0 || (out.PageNumber != 0 && out.PageNumber != cursor.PageNumber) {
				return pagination.Page[*DescribeInstancesOutput]{}, errors.New("inconsistent page response")
			}
			size := out.PageSize
			if size == 0 {
				size = in.PageSize
			}
			// Division avoids signed multiplication overflow; a next page exists only below MaxInt.
			page.HasMore = len(out.Instances) > 0 && out.TotalCount > 0 && cursor.PageNumber <= (out.TotalCount-1)/size
			if page.HasMore {
				page.Next = pagination.Cursor{PageNumber: cursor.PageNumber + 1}
			}
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another service page is available.
func (p *DescribeInstancesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches with isolated per-call options; failed/canceled calls preserve state.
// Options run after ClientOptions and do not persist into later pages.
func (p *DescribeInstancesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInstancesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeInstanceStatusPaginatorOptions controls page size and continuation protection.
// Constructor defaults stop duplicate tokens; callbacks must not retain options.
type DescribeInstanceStatusPaginatorOptions struct {
	// Limit overrides the native page size when positive; zero preserves input/default.
	Limit int
	// StopOnDuplicateToken stops after returning a page with an already seen cursor.
	// Defaults to true. Explicit false may allow unbounded cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies service options to every fetch; NextPage options run last.
	ClientOptions []func(*Options)
}

// DescribeInstanceStatusPaginator traverses reviewed native pagination with one consumer.
// Input pointers/slices and option registrations are copied; do not share or copy it.
type DescribeInstanceStatusPaginator struct {
	engine         *pagination.Paginator[*DescribeInstanceStatusOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeInstanceStatusPaginator copies input and applies dedicated paginator options.
// Zero size uses the reviewed default; errors/cancellation do not advance the cursor.
func NewDescribeInstanceStatusPaginator(api DescribeInstanceStatusAPI, input *DescribeInstanceStatusInput, optFns ...func(*DescribeInstanceStatusPaginatorOptions)) (*DescribeInstanceStatusPaginator, error) {
	if api == nil {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeInstanceStatusPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 {
		return nil, errors.New("negative paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	var in DescribeInstanceStatusInput
	if input != nil {
		in = *input
		in.InstanceIDs = append([]string(nil), input.InstanceIDs...)
	}
	pageMode := true
	initial := pagination.Cursor{}

	if pageMode {
		if in.PageNumber < 0 || in.PageSize < 0 {
			return nil, errors.New("negative page parameters")
		}
		if in.PageNumber == 0 {
			in.PageNumber = 1
		}
		if in.PageSize == 0 {
			in.PageSize = 50
		}
		if options.Limit > 0 {
			in.PageSize = options.Limit
		}
		if in.PageNumber < 1 {
			return nil, errors.New("paginator parameter below minimum")
		}
		if in.PageSize < 1 {
			return nil, errors.New("paginator parameter below minimum")
		}
		if in.PageSize > 50 {
			return nil, errors.New("paginator parameter above maximum")
		}
		initial = pagination.Cursor{PageNumber: in.PageNumber}
	}

	if err := validateStatus(in); err != nil {
		return nil, err
	}
	p := &DescribeInstanceStatusPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeInstanceStatusOutput], error) {
		request := in
		request.InstanceIDs = append([]string(nil), in.InstanceIDs...)

		if pageMode {
			request.PageNumber = cursor.PageNumber
		}

		out, err := api.DescribeInstanceStatus(ctx, &request, p.pendingOptions...)
		if err != nil {
			return pagination.Page[*DescribeInstanceStatusOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeInstanceStatusOutput]{Value: out}

		if pageMode {
			if out.TotalCount < 0 || out.PageSize < 0 || (out.PageNumber != 0 && out.PageNumber != cursor.PageNumber) {
				return pagination.Page[*DescribeInstanceStatusOutput]{}, errors.New("inconsistent page response")
			}
			size := out.PageSize
			if size == 0 {
				size = in.PageSize
			}
			// Division avoids signed multiplication overflow; a next page exists only below MaxInt.
			page.HasMore = len(out.InstanceStatuses) > 0 && out.TotalCount > 0 && cursor.PageNumber <= (out.TotalCount-1)/size
			if page.HasMore {
				page.Next = pagination.Cursor{PageNumber: cursor.PageNumber + 1}
			}
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another service page is available.
func (p *DescribeInstanceStatusPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches with isolated per-call options; failed/canceled calls preserve state.
// Options run after ClientOptions and do not persist into later pages.
func (p *DescribeInstanceStatusPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeInstanceStatusOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// InstanceRunningWaiterOptions controls polling and the reviewed acceptor.
// Callbacks must not retain options; shared extensions must be concurrency safe.
type InstanceRunningWaiterOptions struct {
	// MinDelay is the initial delay; zero selects one second.
	MinDelay time.Duration
	// MaxDelay caps exponential delay; zero selects five seconds.
	MaxDelay time.Duration
	// Now supplies a concurrency-safe clock; nil selects time.Now.
	Now func() time.Time
	// Sleep must honor cancellation; nil selects the shared context-aware sleep.
	Sleep func(context.Context, time.Duration) error
	// ClientOptions applies service options to every poll; registrations are copied.
	ClientOptions []func(*Options)
	// Retryable overrides the default all-ID acceptor. True retries, false succeeds,
	// and an error fails with an inspectable cause. Nil preserves reviewed states.
	// It receives the bounded poll context and a fresh input copy; it must not block.
	// Cancellation/expiry and failed fetches cannot be converted into success.
	Retryable func(context.Context, *DescribeInstanceStatusInput, *DescribeInstanceStatusOutput, error) (bool, error)
}

// InstanceRunningWaiter retains API/options and supports independent concurrent waits.
// Input is copied per invocation and per poll; do not mutate caller input concurrently.
// Default acceptance requires every requested ID in the reviewed success state.
type InstanceRunningWaiter struct {
	api     DescribeInstanceStatusAPI
	options InstanceRunningWaiterOptions
}

// NewInstanceRunningWaiter binds API and copies options without binding a request.
// Unlike AWS constructors, invalid API/options return an error in this early v0 SDK.
func NewInstanceRunningWaiter(api DescribeInstanceStatusAPI, optFns ...func(*InstanceRunningWaiterOptions)) (*InstanceRunningWaiter, error) {
	if api == nil {
		return nil, errors.New("nil waiter API")
	}
	options := InstanceRunningWaiterOptions{}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	minimum, maximum := options.MinDelay, options.MaxDelay
	if minimum == 0 {
		minimum = time.Second
	}
	if maximum == 0 {
		maximum = 5 * time.Second
	}
	if minimum < 0 || maximum < 0 || minimum > maximum {
		return nil, errors.New("invalid waiter delays")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	return &InstanceRunningWaiter{api: api, options: options}, nil
}

// Wait waits for success and discards the output. Input/overrides belong to this wait.
// A positive maxWait includes polls, operation retries and sleeps.
func (w *InstanceRunningWaiter) Wait(ctx context.Context, input *DescribeInstanceStatusInput, maxWait time.Duration, optFns ...func(*InstanceRunningWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, input, maxWait, optFns...)
	return err
}

// WaitForOutput returns the successful response, or nil and an inspectable error.
// It requires 1..50 distinct IDs on the first page. Default acceptance retries
// missing/transitional states and fails unknown/duplicate states or API errors.
// Cancellation passes through; own expiry preserves waiter.ErrTimeout.
func (w *InstanceRunningWaiter) WaitForOutput(ctx context.Context, input *DescribeInstanceStatusInput, maxWait time.Duration, optFns ...func(*InstanceRunningWaiterOptions)) (*DescribeInstanceStatusOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if maxWait <= 0 {
		return nil, errors.New("waiter requires positive maximum wait")
	}
	if input == nil || len(input.InstanceIDs) == 0 || len(input.InstanceIDs) > 50 || input.PageNumber > 1 || input.PageNumber < 0 {
		return nil, errors.New("waiter requires a bounded distinct ID list on the first page")
	}
	in := *input
	in.InstanceIDs = append([]string(nil), input.InstanceIDs...)

	in.PageNumber = 1
	in.PageSize = 50
	options := w.options
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	copiedOptions := append([]func(*Options){}, options.ClientOptions...)
	required := map[string]bool{}
	for _, id := range in.InstanceIDs {
		if id == "" || required[id] {
			return nil, errors.New("invalid waiter IDs")
		}
		required[id] = true
	}
	if err := validateStatus(in); err != nil {
		return nil, err
	}
	var pollContext context.Context
	var decisionError error
	engine, err := waiter.New(func(ctx context.Context) (*DescribeInstanceStatusOutput, error) {
		pollContext = ctx
		request := in
		request.InstanceIDs = append([]string(nil), in.InstanceIDs...)
		return w.api.DescribeInstanceStatus(ctx, &request, append([]func(*Options){}, copiedOptions...)...)
	}, func(out *DescribeInstanceStatusOutput, err error) waiter.Decision {
		decisionError = nil
		if options.Retryable != nil {
			acceptInput := in
			acceptInput.InstanceIDs = append([]string(nil), in.InstanceIDs...)

			again, cause := options.Retryable(pollContext, &acceptInput, out, err)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			if again {
				return waiter.Retry
			}
			if err != nil || out == nil {
				return waiter.Failure
			}
			return waiter.Success
		}
		if err != nil || out == nil {
			return waiter.Failure
		}
		states := map[string]string{}
		for _, entry := range out.InstanceStatuses {
			if !required[entry.InstanceID] {
				continue
			}
			if _, ok := states[entry.InstanceID]; ok {
				return waiter.Failure
			}
			states[entry.InstanceID] = entry.Status
		}
		success := 0
		for id := range required {
			state, present := states[id]
			if !present {
				continue
			}
			switch state {
			case "Running":
				success++
			case "Pending", "Starting", "Stopping", "Stopped":
			default:
				return waiter.Failure
			}
		}
		if success == len(required) {
			return waiter.Success
		}
		return waiter.Retry
	}, waiter.Options{MinDelay: options.MinDelay, MaxDelay: options.MaxDelay, Now: options.Now, Sleep: options.Sleep})
	if err != nil {
		return nil, err
	}
	out, err := engine.Wait(ctx, maxWait)
	if decisionError != nil && errors.Is(err, waiter.ErrFailure) {
		return nil, &waiter.FailureError{Err: decisionError}
	}
	return out, err
}
