// Code generated by sdkgen; DO NOT EDIT.
package ecs

import (
	"context"
	"encoding/json/v2"
	"errors"
	alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"
	"net/url"
	"strconv"
)

// Options aliases shared per-call runtime options.
type Options = alicloud.CallOptions

// Client is a concurrency-safe Ecs client. Construct it with New.
type Client struct{ runtime *alicloud.Client }

// New validates and copies runtime configuration. Custom extension objects must be concurrency safe.
func New(config alicloud.Config) (*Client, error) {
	c, err := alicloud.NewClient(config)
	if err != nil {
		return nil, err
	}
	return &Client{runtime: c}, nil
}

// Instance contains selected response properties.
type Instance struct {
	// InstanceID contains selected wire field InstanceId.
	InstanceID string `json:"InstanceId"`
	// InstanceName contains selected wire field InstanceName.
	InstanceName string `json:"InstanceName"`
	// RegionID contains selected wire field RegionId.
	RegionID string `json:"RegionId"`
	// ZoneID contains selected wire field ZoneId.
	ZoneID string `json:"ZoneId"`
	// Status contains selected wire field Status.
	Status string `json:"Status"`
}

// InstanceStatus contains selected response properties.
type InstanceStatus struct {
	// InstanceID contains selected wire field InstanceId.
	InstanceID string `json:"InstanceId"`
	// Status contains selected wire field Status.
	Status string `json:"Status"`
}

// Region contains selected response properties.
type Region struct {
	// RegionID contains selected wire field RegionId.
	RegionID string `json:"RegionId"`
	// LocalName contains selected wire field LocalName.
	LocalName string `json:"LocalName"`
	// RegionEndpoint contains the service-advertised endpoint; it is not automatically trusted by the endpoint resolver.
	RegionEndpoint string `json:"RegionEndpoint"`
	// Status contains selected wire field Status.
	Status string `json:"Status"`
}

// DescribeInstanceStatusInput contains the selected query parameters; zero optional values are omitted.
type DescribeInstanceStatusInput struct {
	// RegionID defaults to the client region; a per-call region override takes precedence.
	RegionID string
	// InstanceIDs contains up to 100 nonempty IDs; the slice is copied before encoding.
	InstanceIDs []string
	// ZoneID selects wire field ZoneId; zero values are omitted.
	ZoneID string
	// PageNumber selects a one-based page on input; zero omits it. DescribeInstances token and page-number parameters cannot be combined.
	// Nonzero values must be at least 1.
	PageNumber int
	// PageSize selects page size on input; zero omits it (service default ten). DescribeInstances token and page-number parameters cannot be combined.
	// Nonzero values must be at least 1.
	// Nonzero values must be at most 50.
	PageSize int
}

// DescribeInstanceStatusOutput contains selected response fields and transport metadata.
type DescribeInstanceStatusOutput struct {
	// InstanceStatuses contains selected wire field InstanceStatuses.InstanceStatus.
	InstanceStatuses []InstanceStatus
	// TotalCount contains the total count; for DescribeInstances it is meaningful only in legacy page-number mode.
	TotalCount int `json:"TotalCount"`
	// PageNumber selects a one-based page on input; zero omits it. DescribeInstances token and page-number parameters cannot be combined.
	PageNumber int `json:"PageNumber"`
	// PageSize selects page size on input; zero omits it (service default ten). DescribeInstances token and page-number parameters cannot be combined.
	PageSize int `json:"PageSize"`
	// Metadata contains request ID, status and attempt count; it is excluded from wire decoding.
	Metadata alicloud.Metadata `json:"-"`
}

// DescribeInstanceStatusAPI is the minimal operation interface for consumers and fakes.
type DescribeInstanceStatusAPI interface {
	// DescribeInstanceStatus executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
	DescribeInstanceStatus(context.Context, *DescribeInstanceStatusInput, ...func(*Options)) (*DescribeInstanceStatusOutput, error)
}

// DescribeInstanceStatus executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
// API version 2014-05-26. Errors preserve cancellation and structured service causes.
func (c *Client) DescribeInstanceStatus(ctx context.Context, input *DescribeInstanceStatusInput, opts ...func(*Options)) (*DescribeInstanceStatusOutput, error) {
	fail := func(err error) (*DescribeInstanceStatusOutput, error) {
		return nil, generatedValidation(ctx, "DescribeInstanceStatus", err)
	}
	if err := ctx.Err(); err != nil {
		return fail(err)
	}
	var in DescribeInstanceStatusInput
	if input != nil {
		in = *input
		in.InstanceIDs = append([]string(nil), input.InstanceIDs...)
	}
	if err := validateStatus(in); err != nil {
		return fail(err)
	}
	region := ""
	q := url.Values{}
	region = in.RegionID
	if region == "" {
		region = c.runtime.Region()
	}
	q.Set("RegionId", region)
	if len(in.InstanceIDs) > 100 {
		return fail(errors.New("array too large: InstanceId"))
	}
	for i, value := range in.InstanceIDs {
		q.Set("InstanceId."+strconv.Itoa(i+1), value)
	}
	if in.ZoneID != "" {
		q.Set("ZoneId", in.ZoneID)
	}
	if in.PageNumber != 0 && in.PageNumber < 1 {
		return fail(errors.New("parameter below minimum: PageNumber"))
	}
	if in.PageNumber != 0 {
		q.Set("PageNumber", strconv.Itoa(in.PageNumber))
	}
	if in.PageSize != 0 && in.PageSize < 1 {
		return fail(errors.New("parameter below minimum: PageSize"))
	}
	if in.PageSize != 0 && in.PageSize > 50 {
		return fail(errors.New("parameter above maximum: PageSize"))
	}
	if in.PageSize != 0 {
		q.Set("PageSize", strconv.Itoa(in.PageSize))
	}
	var wire struct {
		W0 struct {
			W0 []InstanceStatus `json:"InstanceStatus"`
		} `json:"InstanceStatuses"`
		W1 int `json:"PageNumber"`
		W2 int `json:"PageSize"`
		W3 int `json:"TotalCount"`
	}
	meta, err := c.runtime.Invoke(ctx, alicloud.Operation{Service: "ecs", Name: "DescribeInstanceStatus", Version: "2014-05-26", Idempotent: true}, alicloud.Request{Method: "POST", Path: "/", Region: region, Query: q, Header: map[string][]string{"Content-Type": {"application/x-www-form-urlencoded"}}}, &wire, opts...)
	if err != nil {
		return nil, err
	}
	return &DescribeInstanceStatusOutput{Metadata: meta, InstanceStatuses: wire.W0.W0, TotalCount: wire.W3, PageNumber: wire.W1, PageSize: wire.W2}, nil
}

// DescribeInstancesInput contains the selected query parameters; zero optional values are omitted.
type DescribeInstancesInput struct {
	// RegionID defaults to the client region; a per-call region override takes precedence.
	RegionID string
	// InstanceIDs contains up to 100 nonempty IDs; the slice is copied before encoding.
	InstanceIDs []string
	// ZoneID selects wire field ZoneId; zero values are omitted.
	ZoneID string
	// Status selects wire field Status; zero values are omitted.
	Status string
	// NextToken selects a continuation token on input; an empty output token ends token pagination.
	NextToken string
	// MaxResults selects token page size; zero omits it and the service defaults to ten. Token and page-number parameters cannot be combined.
	// Nonzero values must be at least 1.
	// Nonzero values must be at most 100.
	MaxResults int
	// PageNumber selects a one-based page on input; zero omits it. DescribeInstances token and page-number parameters cannot be combined.
	// Nonzero values must be at least 1.
	PageNumber int
	// PageSize selects page size on input; zero omits it (service default ten). DescribeInstances token and page-number parameters cannot be combined.
	// Nonzero values must be at least 1.
	// Nonzero values must be at most 100.
	PageSize int
}

// DescribeInstancesOutput contains selected response fields and transport metadata.
type DescribeInstancesOutput struct {
	// Instances contains selected wire field Instances.Instance.
	Instances []Instance
	// NextToken selects a continuation token on input; an empty output token ends token pagination.
	NextToken string `json:"NextToken"`
	// PageNumber selects a one-based page on input; zero omits it. DescribeInstances token and page-number parameters cannot be combined.
	PageNumber int `json:"PageNumber"`
	// PageSize selects page size on input; zero omits it (service default ten). DescribeInstances token and page-number parameters cannot be combined.
	PageSize int `json:"PageSize"`
	// TotalCount contains the total count; for DescribeInstances it is meaningful only in legacy page-number mode.
	TotalCount int `json:"TotalCount"`
	// Metadata contains request ID, status and attempt count; it is excluded from wire decoding.
	Metadata alicloud.Metadata `json:"-"`
}

// DescribeInstancesAPI is the minimal operation interface for consumers and fakes.
type DescribeInstancesAPI interface {
	// DescribeInstances executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
	DescribeInstances(context.Context, *DescribeInstancesInput, ...func(*Options)) (*DescribeInstancesOutput, error)
}

// DescribeInstances executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
// API version 2014-05-26. Errors preserve cancellation and structured service causes.
func (c *Client) DescribeInstances(ctx context.Context, input *DescribeInstancesInput, opts ...func(*Options)) (*DescribeInstancesOutput, error) {
	fail := func(err error) (*DescribeInstancesOutput, error) {
		return nil, generatedValidation(ctx, "DescribeInstances", err)
	}
	if err := ctx.Err(); err != nil {
		return fail(err)
	}
	var in DescribeInstancesInput
	if input != nil {
		in = *input
		in.InstanceIDs = append([]string(nil), input.InstanceIDs...)
	}
	if err := validateInstances(in); err != nil {
		return fail(err)
	}
	region := ""
	q := url.Values{}
	region = in.RegionID
	if region == "" {
		region = c.runtime.Region()
	}
	q.Set("RegionId", region)
	if len(in.InstanceIDs) > 0 {
		encoded, err := json.Marshal(in.InstanceIDs)
		if err != nil {
			return fail(err)
		}
		q.Set("InstanceIds", string(encoded))
	}
	if in.ZoneID != "" {
		q.Set("ZoneId", in.ZoneID)
	}
	if in.Status != "" {
		q.Set("Status", in.Status)
	}
	if in.NextToken != "" {
		q.Set("NextToken", in.NextToken)
	}
	if in.MaxResults != 0 && in.MaxResults < 1 {
		return fail(errors.New("parameter below minimum: MaxResults"))
	}
	if in.MaxResults != 0 && in.MaxResults > 100 {
		return fail(errors.New("parameter above maximum: MaxResults"))
	}
	if in.MaxResults != 0 {
		q.Set("MaxResults", strconv.Itoa(in.MaxResults))
	}
	if in.PageNumber != 0 && in.PageNumber < 1 {
		return fail(errors.New("parameter below minimum: PageNumber"))
	}
	if in.PageNumber != 0 {
		q.Set("PageNumber", strconv.Itoa(in.PageNumber))
	}
	if in.PageSize != 0 && in.PageSize < 1 {
		return fail(errors.New("parameter below minimum: PageSize"))
	}
	if in.PageSize != 0 && in.PageSize > 100 {
		return fail(errors.New("parameter above maximum: PageSize"))
	}
	if in.PageSize != 0 {
		q.Set("PageSize", strconv.Itoa(in.PageSize))
	}
	var wire struct {
		W0 struct {
			W0 []Instance `json:"Instance"`
		} `json:"Instances"`
		W1 string `json:"NextToken"`
		W2 int    `json:"PageNumber"`
		W3 int    `json:"PageSize"`
		W4 int    `json:"TotalCount"`
	}
	meta, err := c.runtime.Invoke(ctx, alicloud.Operation{Service: "ecs", Name: "DescribeInstances", Version: "2014-05-26", Idempotent: true}, alicloud.Request{Method: "POST", Path: "/", Region: region, Query: q, Header: map[string][]string{"Content-Type": {"application/x-www-form-urlencoded"}}}, &wire, opts...)
	if err != nil {
		return nil, err
	}
	return &DescribeInstancesOutput{Metadata: meta, Instances: wire.W0.W0, NextToken: wire.W1, PageNumber: wire.W2, PageSize: wire.W3, TotalCount: wire.W4}, nil
}

// DescribeRegionsInput contains the selected query parameters; zero optional values are omitted.
type DescribeRegionsInput struct {
	// AcceptLanguage selects wire field AcceptLanguage; zero values are omitted.
	AcceptLanguage string
	// InstanceChargeType selects wire field InstanceChargeType; zero values are omitted.
	InstanceChargeType string
	// ResourceType selects wire field ResourceType; zero values are omitted.
	ResourceType string
}

// DescribeRegionsOutput contains selected response fields and transport metadata.
type DescribeRegionsOutput struct {
	// Regions contains selected wire field Regions.Region.
	Regions []Region
	// Metadata contains request ID, status and attempt count; it is excluded from wire decoding.
	Metadata alicloud.Metadata `json:"-"`
}

// DescribeRegionsAPI is the minimal operation interface for consumers and fakes.
type DescribeRegionsAPI interface {
	// DescribeRegions executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
	DescribeRegions(context.Context, *DescribeRegionsInput, ...func(*Options)) (*DescribeRegionsOutput, error)
}

// DescribeRegions executes one RPC request through the shared runtime; nil input uses zero values unless required. Callers must not mutate input concurrently.
// API version 2014-05-26. Errors preserve cancellation and structured service causes.
func (c *Client) DescribeRegions(ctx context.Context, input *DescribeRegionsInput, opts ...func(*Options)) (*DescribeRegionsOutput, error) {
	fail := func(err error) (*DescribeRegionsOutput, error) {
		return nil, generatedValidation(ctx, "DescribeRegions", err)
	}
	if err := ctx.Err(); err != nil {
		return fail(err)
	}
	var in DescribeRegionsInput
	if input != nil {
		in = *input
	}
	region := ""
	q := url.Values{}
	if in.AcceptLanguage != "" {
		q.Set("AcceptLanguage", in.AcceptLanguage)
	}
	if in.InstanceChargeType != "" {
		q.Set("InstanceChargeType", in.InstanceChargeType)
	}
	if in.ResourceType != "" {
		q.Set("ResourceType", in.ResourceType)
	}
	var wire struct {
		W0 struct {
			W0 []Region `json:"Region"`
		} `json:"Regions"`
	}
	meta, err := c.runtime.Invoke(ctx, alicloud.Operation{Service: "ecs", Name: "DescribeRegions", Version: "2014-05-26", Idempotent: true}, alicloud.Request{Method: "POST", Path: "/", Region: region, Query: q, Header: map[string][]string{"Content-Type": {"application/x-www-form-urlencoded"}}}, &wire, opts...)
	if err != nil {
		return nil, err
	}
	return &DescribeRegionsOutput{Metadata: meta, Regions: wire.W0.W0}, nil
}
func generatedValidation(ctx context.Context, name string, err error) error {
	if ctx.Err() != nil {
		err = ctx.Err()
	}
	return &alicloud.OperationError{Service: "ecs", Operation: name, Err: err}
}
