// Code generated by sdkgen product; DO NOT EDIT.
package vpc

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/internal/rpcmodel"
	"github.com/rambow-cloud/alicloud-go-sdk-x/pagination"
	"strconv"
)

// DescribeCustomerGatewaysPaginatorOptions controls native pagination and copied operation options.
type DescribeCustomerGatewaysPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeCustomerGatewaysPaginator is a single-consumer iterator; do not copy or share it.
type DescribeCustomerGatewaysPaginator struct {
	engine         *pagination.Paginator[*DescribeCustomerGatewaysOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeCustomerGatewaysPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeCustomerGatewaysPaginator(api DescribeCustomerGatewaysAPI, input *DescribeCustomerGatewaysInput, optFns ...func(*DescribeCustomerGatewaysPaginatorOptions)) (*DescribeCustomerGatewaysPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeCustomerGatewaysPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeCustomerGatewaysInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeCustomerGatewaysPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeCustomerGatewaysOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeCustomerGatewaysOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeCustomerGateways(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeCustomerGatewaysOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeCustomerGatewaysOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeCustomerGatewaysOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeCustomerGatewaysOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeCustomerGatewaysOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeCustomerGatewaysOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeCustomerGatewaysOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeCustomerGatewaysOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.CustomerGateways != nil {
				count = len(out.CustomerGateways.CustomerGateway)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeCustomerGatewaysPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeCustomerGatewaysPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeCustomerGatewaysOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeEcGrantRelationPaginatorOptions controls native pagination and copied operation options.
type DescribeEcGrantRelationPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeEcGrantRelationPaginator is a single-consumer iterator; do not copy or share it.
type DescribeEcGrantRelationPaginator struct {
	engine         *pagination.Paginator[*DescribeEcGrantRelationOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeEcGrantRelationPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeEcGrantRelationPaginator(api DescribeEcGrantRelationAPI, input *DescribeEcGrantRelationInput, optFns ...func(*DescribeEcGrantRelationPaginatorOptions)) (*DescribeEcGrantRelationPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeEcGrantRelationPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeEcGrantRelationInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int64(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int64(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int64(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(^uint(0)>>1) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeEcGrantRelationPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeEcGrantRelationOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeEcGrantRelationOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int64(cursor.PageNumber))
		}

		out, err := api.DescribeEcGrantRelation(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeEcGrantRelationOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeEcGrantRelationOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeEcGrantRelationOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeEcGrantRelationOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeEcGrantRelationOutput]{}, errors.New("invalid page total")
			}
			if out.Page != nil {
				number, cause := rpcmodel.PaginationInteger(*out.Page)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeEcGrantRelationOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeEcGrantRelationOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeEcGrantRelationOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if true {
				count = len(out.EcGrantRelations)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(^uint(0)>>1) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeEcGrantRelationPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeEcGrantRelationPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeEcGrantRelationOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeEipAddressesPaginatorOptions controls native pagination and copied operation options.
type DescribeEipAddressesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeEipAddressesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeEipAddressesPaginator struct {
	engine         *pagination.Paginator[*DescribeEipAddressesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeEipAddressesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeEipAddressesPaginator(api DescribeEipAddressesAPI, input *DescribeEipAddressesInput, optFns ...func(*DescribeEipAddressesPaginatorOptions)) (*DescribeEipAddressesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeEipAddressesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeEipAddressesInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 100 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeEipAddressesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeEipAddressesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeEipAddressesOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeEipAddresses(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeEipAddressesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeEipAddressesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeEipAddressesOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeEipAddressesOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeEipAddressesOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeEipAddressesOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeEipAddressesOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 100 {
				return pagination.Page[*DescribeEipAddressesOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.EIPAddresses != nil {
				count = len(out.EIPAddresses.EIPAddress)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeEipAddressesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeEipAddressesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeEipAddressesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeGrantRulesToEcrPaginatorOptions controls native pagination and copied operation options.
type DescribeGrantRulesToEcrPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeGrantRulesToEcrPaginator is a single-consumer iterator; do not copy or share it.
type DescribeGrantRulesToEcrPaginator struct {
	engine         *pagination.Paginator[*DescribeGrantRulesToEcrOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeGrantRulesToEcrPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeGrantRulesToEcrPaginator(api DescribeGrantRulesToEcrAPI, input *DescribeGrantRulesToEcrInput, optFns ...func(*DescribeGrantRulesToEcrPaginatorOptions)) (*DescribeGrantRulesToEcrPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeGrantRulesToEcrPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeGrantRulesToEcrInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int64(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int64(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int64(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(^uint(0)>>1) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeGrantRulesToEcrPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeGrantRulesToEcrOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int64(cursor.PageNumber))
		}

		out, err := api.DescribeGrantRulesToEcr(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeGrantRulesToEcrOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeGrantRulesToEcrOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if true {
				count = len(out.EcrGrantRules)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(^uint(0)>>1) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeGrantRulesToEcrPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeGrantRulesToEcrPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeGrantRulesToEcrOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeNatGatewaysPaginatorOptions controls native pagination and copied operation options.
type DescribeNatGatewaysPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeNatGatewaysPaginator is a single-consumer iterator; do not copy or share it.
type DescribeNatGatewaysPaginator struct {
	engine         *pagination.Paginator[*DescribeNatGatewaysOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeNatGatewaysPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeNatGatewaysPaginator(api DescribeNatGatewaysAPI, input *DescribeNatGatewaysInput, optFns ...func(*DescribeNatGatewaysPaginatorOptions)) (*DescribeNatGatewaysPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeNatGatewaysPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeNatGatewaysInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeNatGatewaysPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeNatGatewaysOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeNatGatewaysOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeNatGateways(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeNatGatewaysOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeNatGatewaysOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeNatGatewaysOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeNatGatewaysOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeNatGatewaysOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeNatGatewaysOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeNatGatewaysOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeNatGatewaysOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.NATGateways != nil {
				count = len(out.NATGateways.NATGateway)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeNatGatewaysPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeNatGatewaysPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeNatGatewaysOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeRouteEntryListPaginatorOptions controls native pagination and copied operation options.
type DescribeRouteEntryListPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeRouteEntryListPaginator is a single-consumer iterator; do not copy or share it.
type DescribeRouteEntryListPaginator struct {
	engine         *pagination.Paginator[*DescribeRouteEntryListOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeRouteEntryListPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeRouteEntryListPaginator(api DescribeRouteEntryListAPI, input *DescribeRouteEntryListInput, optFns ...func(*DescribeRouteEntryListPaginatorOptions)) (*DescribeRouteEntryListPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeRouteEntryListPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeRouteEntryListInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResult != nil) {
			in.MaxResult = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.MaxResult = rpcmodel.Pointer(int32(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResult)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &DescribeRouteEntryListPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeRouteEntryListOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeRouteEntryListOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.DescribeRouteEntryList(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeRouteEntryListOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeRouteEntryListOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeRouteEntryListOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeRouteEntryListPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeRouteEntryListPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeRouteEntryListOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeRouteTablesPaginatorOptions controls native pagination and copied operation options.
type DescribeRouteTablesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeRouteTablesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeRouteTablesPaginator struct {
	engine         *pagination.Paginator[*DescribeRouteTablesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeRouteTablesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeRouteTablesPaginator(api DescribeRouteTablesAPI, input *DescribeRouteTablesInput, optFns ...func(*DescribeRouteTablesPaginatorOptions)) (*DescribeRouteTablesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeRouteTablesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeRouteTablesInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeRouteTablesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeRouteTablesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeRouteTablesOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeRouteTables(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeRouteTablesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeRouteTablesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeRouteTablesOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeRouteTablesOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeRouteTablesOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeRouteTablesOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeRouteTablesOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeRouteTablesOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.RouteTables != nil {
				count = len(out.RouteTables.RouteTable)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeRouteTablesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeRouteTablesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeRouteTablesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeVSwitchesPaginatorOptions controls native pagination and copied operation options.
type DescribeVSwitchesPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeVSwitchesPaginator is a single-consumer iterator; do not copy or share it.
type DescribeVSwitchesPaginator struct {
	engine         *pagination.Paginator[*DescribeVSwitchesOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeVSwitchesPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeVSwitchesPaginator(api DescribeVSwitchesAPI, input *DescribeVSwitchesInput, optFns ...func(*DescribeVSwitchesPaginatorOptions)) (*DescribeVSwitchesPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeVSwitchesPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeVSwitchesInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeVSwitchesPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeVSwitchesOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeVSwitchesOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeVSwitches(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeVSwitchesOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeVSwitchesOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeVSwitchesOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeVSwitchesOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeVSwitchesOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeVSwitchesOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeVSwitchesOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeVSwitchesOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.VSwitches != nil {
				count = len(out.VSwitches.VSwitch)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeVSwitchesPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeVSwitchesPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeVSwitchesOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeVpcsPaginatorOptions controls native pagination and copied operation options.
type DescribeVpcsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeVpcsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeVpcsPaginator struct {
	engine         *pagination.Paginator[*DescribeVpcsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeVpcsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeVpcsPaginator(api DescribeVpcsAPI, input *DescribeVpcsInput, optFns ...func(*DescribeVpcsPaginatorOptions)) (*DescribeVpcsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeVpcsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeVpcsInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeVpcsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeVpcsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeVpcsOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeVpcs(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeVpcsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeVpcsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeVpcsOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeVpcsOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.Vpcs != nil {
				count = len(out.Vpcs.VPC)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeVpcsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeVpcsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeVpcsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeVpnConnectionsPaginatorOptions controls native pagination and copied operation options.
type DescribeVpnConnectionsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeVpnConnectionsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeVpnConnectionsPaginator struct {
	engine         *pagination.Paginator[*DescribeVpnConnectionsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeVpnConnectionsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeVpnConnectionsPaginator(api DescribeVpnConnectionsAPI, input *DescribeVpnConnectionsInput, optFns ...func(*DescribeVpnConnectionsPaginatorOptions)) (*DescribeVpnConnectionsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeVpnConnectionsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeVpnConnectionsInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeVpnConnectionsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeVpnConnectionsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeVpnConnectionsOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeVpnConnections(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeVpnConnectionsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeVpnConnectionsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeVpnConnectionsOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeVpnConnectionsOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeVpnConnectionsOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeVpnConnectionsOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeVpnConnectionsOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeVpnConnectionsOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.VPNConnections != nil {
				count = len(out.VPNConnections.VPNConnection)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeVpnConnectionsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeVpnConnectionsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeVpnConnectionsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// DescribeVpnGatewaysPaginatorOptions controls native pagination and copied operation options.
type DescribeVpnGatewaysPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeVpnGatewaysPaginator is a single-consumer iterator; do not copy or share it.
type DescribeVpnGatewaysPaginator struct {
	engine         *pagination.Paginator[*DescribeVpnGatewaysOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeVpnGatewaysPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeVpnGatewaysPaginator(api DescribeVpnGatewaysAPI, input *DescribeVpnGatewaysInput, optFns ...func(*DescribeVpnGatewaysPaginatorOptions)) (*DescribeVpnGatewaysPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeVpnGatewaysPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateDescribeVpnGatewaysInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		nativePage, cause := rpcmodel.PaginationInteger(*in.PageNumber)
		if cause != nil || nativePage < 1 || nativePage > int64(2147483647) {
			return nil, errors.New("invalid native page number")
		}
		nativeSize, cause := rpcmodel.PaginationInteger(*in.PageSize)
		if cause != nil || nativeSize < 1 || nativeSize > 50 {
			return nil, errors.New("invalid native page size")
		}
		initial.PageNumber = int(nativePage)
	}

	p := &DescribeVpnGatewaysPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeVpnGatewaysOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeVpnGatewaysOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeVpnGateways(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeVpnGatewaysOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeVpnGatewaysOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeVpnGatewaysOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) {
				return pagination.Page[*DescribeVpnGatewaysOutput]{}, errors.New("missing page total")
			}
			total, cause := rpcmodel.PaginationInteger(*out.TotalCount)
			if cause != nil || total < 0 {
				return pagination.Page[*DescribeVpnGatewaysOutput]{}, errors.New("invalid page total")
			}
			if out.PageNumber != nil {
				number, cause := rpcmodel.PaginationInteger(*out.PageNumber)
				if cause != nil || number != int64(cursor.PageNumber) {
					return pagination.Page[*DescribeVpnGatewaysOutput]{}, errors.New("inconsistent page number")
				}
			}
			size, cause := rpcmodel.PaginationInteger(*in.PageSize)
			if cause != nil {
				return pagination.Page[*DescribeVpnGatewaysOutput]{}, errors.New("invalid request page size")
			}
			if out.PageSize != nil {
				size, cause = rpcmodel.PaginationInteger(*out.PageSize)
			}
			if cause != nil || size < 1 || size > 50 {
				return pagination.Page[*DescribeVpnGatewaysOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.VPNGateways != nil {
				count = len(out.VPNGateways.VPNGateway)
			}
			page.HasMore = count > 0 && total > 0 && int64(cursor.PageNumber) < int64(2147483647) && int64(cursor.PageNumber) <= (total-1)/size
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeVpnGatewaysPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeVpnGatewaysPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeVpnGatewaysOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// ListNatIpCidrsPaginatorOptions controls native pagination and copied operation options.
type ListNatIpCidrsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// ListNatIpCidrsPaginator is a single-consumer iterator; do not copy or share it.
type ListNatIpCidrsPaginator struct {
	engine         *pagination.Paginator[*ListNatIpCidrsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewListNatIpCidrsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewListNatIpCidrsPaginator(api ListNatIpCidrsAPI, input *ListNatIpCidrsInput, optFns ...func(*ListNatIpCidrsPaginatorOptions)) (*ListNatIpCidrsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := ListNatIpCidrsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(strconv.FormatInt(int64(20), 10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(strconv.FormatInt(int64(options.Limit), 10))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &ListNatIpCidrsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*ListNatIpCidrsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*ListNatIpCidrsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.ListNatIpCidrs(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*ListNatIpCidrsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*ListNatIpCidrsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*ListNatIpCidrsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *ListNatIpCidrsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *ListNatIpCidrsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListNatIpCidrsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// ListNatIpsPaginatorOptions controls native pagination and copied operation options.
type ListNatIpsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// ListNatIpsPaginator is a single-consumer iterator; do not copy or share it.
type ListNatIpsPaginator struct {
	engine         *pagination.Paginator[*ListNatIpsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewListNatIpsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewListNatIpsPaginator(api ListNatIpsAPI, input *ListNatIpsInput, optFns ...func(*ListNatIpsPaginatorOptions)) (*ListNatIpsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := ListNatIpsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(strconv.FormatInt(int64(20), 10))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(strconv.FormatInt(int64(options.Limit), 10))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &ListNatIpsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*ListNatIpsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*ListNatIpsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.ListNatIps(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*ListNatIpsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*ListNatIpsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*ListNatIpsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *ListNatIpsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *ListNatIpsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListNatIpsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// ListPrefixListsPaginatorOptions controls native pagination and copied operation options.
type ListPrefixListsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// ListPrefixListsPaginator is a single-consumer iterator; do not copy or share it.
type ListPrefixListsPaginator struct {
	engine         *pagination.Paginator[*ListPrefixListsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewListPrefixListsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewListPrefixListsPaginator(api ListPrefixListsAPI, input *ListPrefixListsInput, optFns ...func(*ListPrefixListsPaginatorOptions)) (*ListPrefixListsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := ListPrefixListsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateListPrefixListsInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int64(20))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int64(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &ListPrefixListsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*ListPrefixListsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*ListPrefixListsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.ListPrefixLists(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*ListPrefixListsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*ListPrefixListsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*ListPrefixListsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *ListPrefixListsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *ListPrefixListsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListPrefixListsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}

// ListVpcGatewayEndpointsPaginatorOptions controls native pagination and copied operation options.
type ListVpcGatewayEndpointsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// ListVpcGatewayEndpointsPaginator is a single-consumer iterator; do not copy or share it.
type ListVpcGatewayEndpointsPaginator struct {
	engine         *pagination.Paginator[*ListVpcGatewayEndpointsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewListVpcGatewayEndpointsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewListVpcGatewayEndpointsPaginator(api ListVpcGatewayEndpointsAPI, input *ListVpcGatewayEndpointsInput, optFns ...func(*ListVpcGatewayEndpointsPaginatorOptions)) (*ListVpcGatewayEndpointsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := ListVpcGatewayEndpointsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 100 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}

	if err := ValidateListVpcGatewayEndpointsInput(in); err != nil {
		return nil, err
	}
	pageMode := false
	initial := pagination.Cursor{}

	if !pageMode {
		if !(in.MaxResults != nil) {
			in.MaxResults = rpcmodel.Pointer(int64(20))
		}
		if options.Limit > 0 {
			in.MaxResults = rpcmodel.Pointer(int64(options.Limit))
		}
		nativeLimit, cause := rpcmodel.PaginationInteger(*in.MaxResults)
		if cause != nil || nativeLimit < 1 || nativeLimit > 100 {
			return nil, errors.New("invalid native token limit")
		}
		if in.NextToken != nil {
			initial.Token = *in.NextToken
		}
	}
	p := &ListVpcGatewayEndpointsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*ListVpcGatewayEndpointsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*ListVpcGatewayEndpointsOutput]{}, err
		}

		if !pageMode {
			request.NextToken = rpcmodel.Pointer(cursor.Token)
		}
		out, err := api.ListVpcGatewayEndpoints(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*ListVpcGatewayEndpointsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*ListVpcGatewayEndpointsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*ListVpcGatewayEndpointsOutput]{Value: out}
		if !pageMode {
			if out.NextToken != nil {
				page.Next.Token = *out.NextToken
			}
			page.HasMore = page.Next.Token != ""
		}

		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *ListVpcGatewayEndpointsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *ListVpcGatewayEndpointsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListVpcGatewayEndpointsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}
