// Code generated by sdkgen product; DO NOT EDIT.
package vpc

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/internal/rpcmodel"
	"github.com/rambow-cloud/alicloud-go-sdk-x/pagination"
)

// DescribeVpcsPaginatorOptions controls native pagination and copied operation options.
type DescribeVpcsPaginatorOptions struct {
	// Limit overrides native page size; zero preserves input or the reviewed default.
	Limit int
	// StopOnDuplicateToken defaults true and returns the fetched page before stopping.
	// Explicit false can permit cyclic traversal.
	StopOnDuplicateToken bool
	// ClientOptions applies to every page; NextPage overrides run last for that page only.
	ClientOptions []func(*Options)
}

// DescribeVpcsPaginator is a single-consumer iterator; do not copy or share it.
type DescribeVpcsPaginator struct {
	engine         *pagination.Paginator[*DescribeVpcsOutput]
	clientOptions  []func(*Options)
	pendingOptions []func(*Options)
}

// NewDescribeVpcsPaginator snapshots input and applies reviewed native pagination.
// Invalid API/options/fields return errors; constructor errors are an intentional v0 convention.
func NewDescribeVpcsPaginator(api DescribeVpcsAPI, input *DescribeVpcsInput, optFns ...func(*DescribeVpcsPaginatorOptions)) (*DescribeVpcsPaginator, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil paginator API")
	}
	options := DescribeVpcsPaginatorOptions{StopOnDuplicateToken: true}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil paginator option")
		}
		f(&options)
	}
	if options.Limit < 0 || options.Limit > 50 {
		return nil, errors.New("invalid paginator limit")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil paginator client option")
		}
	}
	in, err := rpcmodel.Snapshot(context.Background(), input)
	if err != nil {
		return nil, err
	}
	if err := ValidateDescribeVpcsInput(in); err != nil {
		return nil, err
	}
	pageMode := true
	initial := pagination.Cursor{}
	if pageMode {
		if !(in.PageNumber != nil) {
			in.PageNumber = rpcmodel.Pointer(int32(1))
		}
		if !(in.PageSize != nil) {
			in.PageSize = rpcmodel.Pointer(int32(10))
		}
		if options.Limit > 0 {
			in.PageSize = rpcmodel.Pointer(int32(options.Limit))
		}
		if *in.PageNumber < 1 || *in.PageSize < 1 || *in.PageSize > 50 {
			return nil, errors.New("invalid native page fields")
		}
		initial.PageNumber = int(*in.PageNumber)
	}

	p := &DescribeVpcsPaginator{clientOptions: append([]func(*Options){}, options.ClientOptions...)}
	engine, err := pagination.New(initial, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeVpcsOutput], error) {
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return pagination.Page[*DescribeVpcsOutput]{}, err
		}
		if pageMode {
			request.PageNumber = rpcmodel.Pointer(int32(cursor.PageNumber))
		}

		out, err := api.DescribeVpcs(ctx, request, append([]func(*Options){}, p.pendingOptions...)...)
		if err != nil {
			return pagination.Page[*DescribeVpcsOutput]{}, err
		}
		if out == nil {
			return pagination.Page[*DescribeVpcsOutput]{}, errors.New("nil paginator response")
		}
		page := pagination.Page[*DescribeVpcsOutput]{Value: out}

		if pageMode {
			if !(out.TotalCount != nil) || *out.TotalCount < 0 {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("missing or negative page total")
			}
			if out.PageNumber != nil && int(*out.PageNumber) != cursor.PageNumber {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("inconsistent page number")
			}
			size := int(*in.PageSize)
			if out.PageSize != nil {
				size = int(*out.PageSize)
			}
			if size < 1 || size > 50 {
				return pagination.Page[*DescribeVpcsOutput]{}, errors.New("invalid response page size")
			}
			count := 0
			if out.Vpcs != nil {
				count = len(out.Vpcs.VPC)
			}
			page.HasMore = count > 0 && *out.TotalCount > 0 && cursor.PageNumber < 2147483647 && cursor.PageNumber <= int((*out.TotalCount-1)/int32(size))
			if page.HasMore {
				page.Next.PageNumber = cursor.PageNumber + 1
			}
		}
		return page, nil
	}, func(o *pagination.Options) { o.StopOnDuplicateCursor = options.StopOnDuplicateToken })
	if err != nil {
		return nil, err
	}
	p.engine = engine
	return p, nil
}

// HasMorePages reports whether another native page is available; initially true.
func (p *DescribeVpcsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches a page with isolated options. Failed/canceled fetches preserve state.
func (p *DescribeVpcsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*DescribeVpcsOutput, error) {
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil page option")
		}
	}
	p.pendingOptions = append(append([]func(*Options){}, p.clientOptions...), optFns...)
	defer func() { p.pendingOptions = nil }()
	return p.engine.NextPage(ctx)
}
