// Code generated by sdkgen product; DO NOT EDIT.
package vpc

import (
	"errors"
)

// ValidateDescribeVpcsInput checks only the reviewed sparse constraints without changing input.
// Nil is an empty request; diagnostics identify rules without including values.
func ValidateDescribeVpcsInput(in *DescribeVpcsInput) error {
	if in == nil {
		return nil
	}
	if in.PageNumber != nil {
		if *in.PageNumber < 1 {
			return errors.New("invalid PageNumber: below minimum")
		}
	}
	if in.PageSize != nil {
		if *in.PageSize < 1 {
			return errors.New("invalid PageSize: below minimum")
		}
		if *in.PageSize > 50 {
			return errors.New("invalid PageSize: above maximum")
		}
	}
	return nil
}
