// Code generated by sdkgen product; DO NOT EDIT.
package vpc

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/internal/rpcmodel"
	"github.com/rambow-cloud/alicloud-go-sdk-x/waiter"
	"time"
)

// NatGatewayAvailableWaiterOptions configures bounded polling and an optional acceptor override.
// Shared callbacks must be concurrency safe and must not retain options or models.
type NatGatewayAvailableWaiterOptions struct {
	// MinDelay defaults to one second.
	MinDelay time.Duration
	// MaxDelay caps exponential delay and defaults to five seconds.
	MaxDelay time.Duration
	// Now is a concurrency-safe clock; nil uses time.Now.
	Now func() time.Time
	// Sleep honors cancellation; nil uses the shared sleep helper.
	Sleep func(context.Context, time.Duration) error
	// ClientOptions applies to every poll and is copied per invocation.
	ClientOptions []func(*Options)
	// Retryable overrides state acceptance: true retries, false succeeds, error fails.
	// It receives a fresh input and bounded context; failed fetches cannot become success.
	Retryable func(context.Context, *DescribeNatGatewaysInput, *DescribeNatGatewaysOutput, error) (bool, error)
}

// NatGatewayAvailableWaiter is reusable for independent concurrent waits; do not mutate inputs during calls.
type NatGatewayAvailableWaiter struct {
	api     DescribeNatGatewaysAPI
	options NatGatewayAvailableWaiterOptions
}

// NewNatGatewayAvailableWaiter binds an API and copies defaults without binding a request.
// Invalid APIs/options return errors, an intentional v0 constructor convention.
func NewNatGatewayAvailableWaiter(api DescribeNatGatewaysAPI, optFns ...func(*NatGatewayAvailableWaiterOptions)) (*NatGatewayAvailableWaiter, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil waiter API")
	}
	options := NatGatewayAvailableWaiterOptions{}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	minimum, maximum := options.MinDelay, options.MaxDelay
	if minimum == 0 {
		minimum = time.Second
	}
	if maximum == 0 {
		maximum = 5 * time.Second
	}
	if minimum < 0 || maximum < 0 || minimum > maximum {
		return nil, errors.New("invalid waiter delays")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	return &NatGatewayAvailableWaiter{api: api, options: options}, nil
}

// Wait waits for all requested IDs to reach the reviewed success state and discards output.
// Positive maxWait includes operation retries and sleeps; input/options are isolated.
func (w *NatGatewayAvailableWaiter) Wait(ctx context.Context, input *DescribeNatGatewaysInput, maxWait time.Duration, optFns ...func(*NatGatewayAvailableWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, input, maxWait, optFns...)
	return err
}

// WaitForOutput returns success or nil/error; missing IDs retry, unknown/duplicate states fail.
// Caller cancellation passes through; own expiry is inspectable as waiter.ErrTimeout.
func (w *NatGatewayAvailableWaiter) WaitForOutput(ctx context.Context, input *DescribeNatGatewaysInput, maxWait time.Duration, optFns ...func(*NatGatewayAvailableWaiterOptions)) (*DescribeNatGatewaysOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if maxWait <= 0 {
		return nil, errors.New("positive waiter duration required")
	}
	if w == nil || rpcmodel.IsNil(w.api) {
		return nil, errors.New("uninitialized waiter")
	}
	in, err := rpcmodel.Snapshot(ctx, input)
	if err != nil {
		return nil, err
	}
	if !(in.NATGatewayID != nil) {
		return nil, errors.New("waiter requires resource ID")
	}
	requestedIDs := []string{*in.NATGatewayID}
	if len(requestedIDs) < 1 || len(requestedIDs) > 1 {
		return nil, errors.New("waiter requires bounded ID list")
	}
	if err := ValidateDescribeNatGatewaysInput(in); err != nil {
		return nil, err
	}
	if in.PageNumber != nil && *in.PageNumber != 1 {
		return nil, errors.New("waiter requires first page")
	}
	in.PageNumber = rpcmodel.Pointer(int32(1))
	in.PageSize = rpcmodel.Pointer(int32(1))
	required := map[string]bool{}
	for _, id := range requestedIDs {
		if id == "" || required[id] {
			return nil, errors.New("waiter requires distinct nonempty IDs")
		}
		required[id] = true
	}
	options := w.options
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	copiedOptions := append([]func(*Options){}, options.ClientOptions...)
	var pollContext context.Context
	var decisionError error
	engine, err := waiter.New(func(ctx context.Context) (*DescribeNatGatewaysOutput, error) {
		pollContext = ctx
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return nil, err
		}
		return w.api.DescribeNatGateways(ctx, request, append([]func(*Options){}, copiedOptions...)...)
	}, func(out *DescribeNatGatewaysOutput, err error) waiter.Decision {
		decisionError = nil
		if out == nil && err == nil {
			decisionError = errors.New("nil waiter response")
			return waiter.Failure
		}
		if options.Retryable != nil {
			owned, cause := rpcmodel.Snapshot(pollContext, in)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			again, cause := options.Retryable(pollContext, owned, out, err)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			if again {
				return waiter.Retry
			}
			if err != nil {
				return waiter.Failure
			}
			return waiter.Success
		}
		if err != nil || out == nil {
			return waiter.Failure
		}
		seen := map[string]bool{}
		running := 0
		if out.NATGateways != nil {
			for _, item := range out.NATGateways.NATGateway {
				if !(item.NATGatewayID != nil) {
					return waiter.Failure
				}
				id := *item.NATGatewayID
				if !required[id] {
					continue
				}
				if seen[id] || !(item.Status != nil) {
					return waiter.Failure
				}
				seen[id] = true
				switch *item.Status {
				case "Available":
					running++
				case "Creating", "Modifying", "Converting":
				default:
					return waiter.Failure
				}
			}
		}
		if running == len(required) {
			return waiter.Success
		}
		return waiter.Retry
	}, waiter.Options{MinDelay: options.MinDelay, MaxDelay: options.MaxDelay, Now: options.Now, Sleep: options.Sleep})
	if err != nil {
		return nil, err
	}
	out, err := engine.Wait(ctx, maxWait)
	if decisionError != nil && errors.Is(err, waiter.ErrFailure) {
		return nil, &waiter.FailureError{Err: decisionError}
	}
	return out, err
}

// VSwitchAvailableWaiterOptions configures bounded polling and an optional acceptor override.
// Shared callbacks must be concurrency safe and must not retain options or models.
type VSwitchAvailableWaiterOptions struct {
	// MinDelay defaults to one second.
	MinDelay time.Duration
	// MaxDelay caps exponential delay and defaults to five seconds.
	MaxDelay time.Duration
	// Now is a concurrency-safe clock; nil uses time.Now.
	Now func() time.Time
	// Sleep honors cancellation; nil uses the shared sleep helper.
	Sleep func(context.Context, time.Duration) error
	// ClientOptions applies to every poll and is copied per invocation.
	ClientOptions []func(*Options)
	// Retryable overrides state acceptance: true retries, false succeeds, error fails.
	// It receives a fresh input and bounded context; failed fetches cannot become success.
	Retryable func(context.Context, *DescribeVSwitchesInput, *DescribeVSwitchesOutput, error) (bool, error)
}

// VSwitchAvailableWaiter is reusable for independent concurrent waits; do not mutate inputs during calls.
type VSwitchAvailableWaiter struct {
	api     DescribeVSwitchesAPI
	options VSwitchAvailableWaiterOptions
}

// NewVSwitchAvailableWaiter binds an API and copies defaults without binding a request.
// Invalid APIs/options return errors, an intentional v0 constructor convention.
func NewVSwitchAvailableWaiter(api DescribeVSwitchesAPI, optFns ...func(*VSwitchAvailableWaiterOptions)) (*VSwitchAvailableWaiter, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil waiter API")
	}
	options := VSwitchAvailableWaiterOptions{}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	minimum, maximum := options.MinDelay, options.MaxDelay
	if minimum == 0 {
		minimum = time.Second
	}
	if maximum == 0 {
		maximum = 5 * time.Second
	}
	if minimum < 0 || maximum < 0 || minimum > maximum {
		return nil, errors.New("invalid waiter delays")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	return &VSwitchAvailableWaiter{api: api, options: options}, nil
}

// Wait waits for all requested IDs to reach the reviewed success state and discards output.
// Positive maxWait includes operation retries and sleeps; input/options are isolated.
func (w *VSwitchAvailableWaiter) Wait(ctx context.Context, input *DescribeVSwitchesInput, maxWait time.Duration, optFns ...func(*VSwitchAvailableWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, input, maxWait, optFns...)
	return err
}

// WaitForOutput returns success or nil/error; missing IDs retry, unknown/duplicate states fail.
// Caller cancellation passes through; own expiry is inspectable as waiter.ErrTimeout.
func (w *VSwitchAvailableWaiter) WaitForOutput(ctx context.Context, input *DescribeVSwitchesInput, maxWait time.Duration, optFns ...func(*VSwitchAvailableWaiterOptions)) (*DescribeVSwitchesOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if maxWait <= 0 {
		return nil, errors.New("positive waiter duration required")
	}
	if w == nil || rpcmodel.IsNil(w.api) {
		return nil, errors.New("uninitialized waiter")
	}
	in, err := rpcmodel.Snapshot(ctx, input)
	if err != nil {
		return nil, err
	}
	if !(in.VSwitchID != nil) {
		return nil, errors.New("waiter requires resource ID")
	}
	requestedIDs := []string{*in.VSwitchID}
	if len(requestedIDs) < 1 || len(requestedIDs) > 1 {
		return nil, errors.New("waiter requires bounded ID list")
	}
	if err := ValidateDescribeVSwitchesInput(in); err != nil {
		return nil, err
	}
	if in.PageNumber != nil && *in.PageNumber != 1 {
		return nil, errors.New("waiter requires first page")
	}
	in.PageNumber = rpcmodel.Pointer(int32(1))
	in.PageSize = rpcmodel.Pointer(int32(1))
	required := map[string]bool{}
	for _, id := range requestedIDs {
		if id == "" || required[id] {
			return nil, errors.New("waiter requires distinct nonempty IDs")
		}
		required[id] = true
	}
	options := w.options
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	copiedOptions := append([]func(*Options){}, options.ClientOptions...)
	var pollContext context.Context
	var decisionError error
	engine, err := waiter.New(func(ctx context.Context) (*DescribeVSwitchesOutput, error) {
		pollContext = ctx
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return nil, err
		}
		return w.api.DescribeVSwitches(ctx, request, append([]func(*Options){}, copiedOptions...)...)
	}, func(out *DescribeVSwitchesOutput, err error) waiter.Decision {
		decisionError = nil
		if out == nil && err == nil {
			decisionError = errors.New("nil waiter response")
			return waiter.Failure
		}
		if options.Retryable != nil {
			owned, cause := rpcmodel.Snapshot(pollContext, in)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			again, cause := options.Retryable(pollContext, owned, out, err)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			if again {
				return waiter.Retry
			}
			if err != nil {
				return waiter.Failure
			}
			return waiter.Success
		}
		if err != nil || out == nil {
			return waiter.Failure
		}
		seen := map[string]bool{}
		running := 0
		if out.VSwitches != nil {
			for _, item := range out.VSwitches.VSwitch {
				if !(item.VSwitchID != nil) {
					return waiter.Failure
				}
				id := *item.VSwitchID
				if !required[id] {
					continue
				}
				if seen[id] || !(item.Status != nil) {
					return waiter.Failure
				}
				seen[id] = true
				switch *item.Status {
				case "Available":
					running++
				case "Pending":
				default:
					return waiter.Failure
				}
			}
		}
		if running == len(required) {
			return waiter.Success
		}
		return waiter.Retry
	}, waiter.Options{MinDelay: options.MinDelay, MaxDelay: options.MaxDelay, Now: options.Now, Sleep: options.Sleep})
	if err != nil {
		return nil, err
	}
	out, err := engine.Wait(ctx, maxWait)
	if decisionError != nil && errors.Is(err, waiter.ErrFailure) {
		return nil, &waiter.FailureError{Err: decisionError}
	}
	return out, err
}

// VpcAvailableWaiterOptions configures bounded polling and an optional acceptor override.
// Shared callbacks must be concurrency safe and must not retain options or models.
type VpcAvailableWaiterOptions struct {
	// MinDelay defaults to one second.
	MinDelay time.Duration
	// MaxDelay caps exponential delay and defaults to five seconds.
	MaxDelay time.Duration
	// Now is a concurrency-safe clock; nil uses time.Now.
	Now func() time.Time
	// Sleep honors cancellation; nil uses the shared sleep helper.
	Sleep func(context.Context, time.Duration) error
	// ClientOptions applies to every poll and is copied per invocation.
	ClientOptions []func(*Options)
	// Retryable overrides state acceptance: true retries, false succeeds, error fails.
	// It receives a fresh input and bounded context; failed fetches cannot become success.
	Retryable func(context.Context, *DescribeVpcsInput, *DescribeVpcsOutput, error) (bool, error)
}

// VpcAvailableWaiter is reusable for independent concurrent waits; do not mutate inputs during calls.
type VpcAvailableWaiter struct {
	api     DescribeVpcsAPI
	options VpcAvailableWaiterOptions
}

// NewVpcAvailableWaiter binds an API and copies defaults without binding a request.
// Invalid APIs/options return errors, an intentional v0 constructor convention.
func NewVpcAvailableWaiter(api DescribeVpcsAPI, optFns ...func(*VpcAvailableWaiterOptions)) (*VpcAvailableWaiter, error) {
	if rpcmodel.IsNil(api) {
		return nil, errors.New("nil waiter API")
	}
	options := VpcAvailableWaiterOptions{}
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	minimum, maximum := options.MinDelay, options.MaxDelay
	if minimum == 0 {
		minimum = time.Second
	}
	if maximum == 0 {
		maximum = 5 * time.Second
	}
	if minimum < 0 || maximum < 0 || minimum > maximum {
		return nil, errors.New("invalid waiter delays")
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	return &VpcAvailableWaiter{api: api, options: options}, nil
}

// Wait waits for all requested IDs to reach the reviewed success state and discards output.
// Positive maxWait includes operation retries and sleeps; input/options are isolated.
func (w *VpcAvailableWaiter) Wait(ctx context.Context, input *DescribeVpcsInput, maxWait time.Duration, optFns ...func(*VpcAvailableWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, input, maxWait, optFns...)
	return err
}

// WaitForOutput returns success or nil/error; missing IDs retry, unknown/duplicate states fail.
// Caller cancellation passes through; own expiry is inspectable as waiter.ErrTimeout.
func (w *VpcAvailableWaiter) WaitForOutput(ctx context.Context, input *DescribeVpcsInput, maxWait time.Duration, optFns ...func(*VpcAvailableWaiterOptions)) (*DescribeVpcsOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if maxWait <= 0 {
		return nil, errors.New("positive waiter duration required")
	}
	if w == nil || rpcmodel.IsNil(w.api) {
		return nil, errors.New("uninitialized waiter")
	}
	in, err := rpcmodel.Snapshot(ctx, input)
	if err != nil {
		return nil, err
	}
	if !(in.VPCID != nil) {
		return nil, errors.New("waiter requires resource ID")
	}
	requestedIDs := []string{*in.VPCID}
	if len(requestedIDs) < 1 || len(requestedIDs) > 1 {
		return nil, errors.New("waiter requires bounded ID list")
	}
	if err := ValidateDescribeVpcsInput(in); err != nil {
		return nil, err
	}
	if in.PageNumber != nil && *in.PageNumber != 1 {
		return nil, errors.New("waiter requires first page")
	}
	in.PageNumber = rpcmodel.Pointer(int32(1))
	in.PageSize = rpcmodel.Pointer(int32(1))
	required := map[string]bool{}
	for _, id := range requestedIDs {
		if id == "" || required[id] {
			return nil, errors.New("waiter requires distinct nonempty IDs")
		}
		required[id] = true
	}
	options := w.options
	options.ClientOptions = append([]func(*Options){}, options.ClientOptions...)
	for _, f := range optFns {
		if f == nil {
			return nil, errors.New("nil waiter option")
		}
		f(&options)
	}
	for _, f := range options.ClientOptions {
		if f == nil {
			return nil, errors.New("nil waiter client option")
		}
	}
	copiedOptions := append([]func(*Options){}, options.ClientOptions...)
	var pollContext context.Context
	var decisionError error
	engine, err := waiter.New(func(ctx context.Context) (*DescribeVpcsOutput, error) {
		pollContext = ctx
		request, err := rpcmodel.Snapshot(ctx, in)
		if err != nil {
			return nil, err
		}
		return w.api.DescribeVpcs(ctx, request, append([]func(*Options){}, copiedOptions...)...)
	}, func(out *DescribeVpcsOutput, err error) waiter.Decision {
		decisionError = nil
		if out == nil && err == nil {
			decisionError = errors.New("nil waiter response")
			return waiter.Failure
		}
		if options.Retryable != nil {
			owned, cause := rpcmodel.Snapshot(pollContext, in)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			again, cause := options.Retryable(pollContext, owned, out, err)
			if cause != nil {
				decisionError = cause
				return waiter.Failure
			}
			if again {
				return waiter.Retry
			}
			if err != nil {
				return waiter.Failure
			}
			return waiter.Success
		}
		if err != nil || out == nil {
			return waiter.Failure
		}
		seen := map[string]bool{}
		running := 0
		if out.Vpcs != nil {
			for _, item := range out.Vpcs.VPC {
				if !(item.VPCID != nil) {
					return waiter.Failure
				}
				id := *item.VPCID
				if !required[id] {
					continue
				}
				if seen[id] || !(item.Status != nil) {
					return waiter.Failure
				}
				seen[id] = true
				switch *item.Status {
				case "Available":
					running++
				case "Pending":
				default:
					return waiter.Failure
				}
			}
		}
		if running == len(required) {
			return waiter.Success
		}
		return waiter.Retry
	}, waiter.Options{MinDelay: options.MinDelay, MaxDelay: options.MaxDelay, Now: options.Now, Sleep: options.Sleep})
	if err != nil {
		return nil, err
	}
	out, err := engine.Wait(ctx, maxWait)
	if decisionError != nil && errors.Is(err, waiter.ErrFailure) {
		return nil, &waiter.FailureError{Err: decisionError}
	}
	return out, err
}
