// Code generated by sdkgen; DO NOT EDIT.
package vpc

import (
	"context"
	"errors"
	"github.com/rambow-cloud/alicloud-go-sdk-x/pagination"
)

// DescribeVpcsPaginator traverses reviewed page-number results using the shared engine.
// Use one consumer; the original input and pointer/slice members are copied.
type DescribeVpcsPaginator struct {
	engine *pagination.Paginator[*DescribeVpcsOutput]
}

// NewDescribeVpcsPaginator starts at the supplied page, defaulting to page one.
// A zero page size uses the reviewed default; service failures do not advance.
func NewDescribeVpcsPaginator(api DescribeVpcsAPI, input *DescribeVpcsInput, opts ...func(*Options)) (*DescribeVpcsPaginator, error) {
	if api == nil {
		return nil, errors.New("nil paginator API")
	}
	var in DescribeVpcsInput
	if input != nil {
		in = *input
		if input.IsDefault != nil {
			copied := *input.IsDefault
			in.IsDefault = &copied
		}
		if input.DryRun != nil {
			copied := *input.DryRun
			in.DryRun = &copied
		}
		if input.IPv6Enabled != nil {
			copied := *input.IPv6Enabled
			in.IPv6Enabled = &copied
		}
		in.Tags = append([]TagFilter(nil), input.Tags...)
		for i := range in.Tags {
			in.Tags[i] = cloneTagFilter(in.Tags[i])
		}
	}
	if err := validateDescribeVpcs(in); err != nil {
		return nil, err
	}
	if in.PageNumber < 0 || in.PageSize < 0 {
		return nil, errors.New("negative page parameters")
	}
	if in.PageNumber == 0 {
		in.PageNumber = 1
	}
	if in.PageSize == 0 {
		in.PageSize = 10
	}
	copiedOptions := append([]func(*Options){}, opts...)
	engine, err := pagination.New(pagination.Cursor{PageNumber: in.PageNumber}, func(ctx context.Context, cursor pagination.Cursor) (pagination.Page[*DescribeVpcsOutput], error) {
		request := in
		if in.IsDefault != nil {
			copied := *in.IsDefault
			request.IsDefault = &copied
		}
		if in.DryRun != nil {
			copied := *in.DryRun
			request.DryRun = &copied
		}
		if in.IPv6Enabled != nil {
			copied := *in.IPv6Enabled
			request.IPv6Enabled = &copied
		}
		request.Tags = append([]TagFilter(nil), in.Tags...)
		for i := range request.Tags {
			request.Tags[i] = cloneTagFilter(request.Tags[i])
		}
		request.PageNumber = cursor.PageNumber
		out, err := api.DescribeVpcs(ctx, &request, copiedOptions...)
		if err != nil {
			return pagination.Page[*DescribeVpcsOutput]{}, err
		}
		if out == nil || out.TotalCount < 0 || out.PageSize < 0 || (out.PageNumber != 0 && out.PageNumber != cursor.PageNumber) {
			return pagination.Page[*DescribeVpcsOutput]{}, errors.New("inconsistent page response")
		}
		size := out.PageSize
		if size == 0 {
			size = in.PageSize
		}
		// Division keeps total/position comparisons safe at the machine integer limit.
		more := len(out.VPCs) > 0 && out.TotalCount > 0 && cursor.PageNumber <= (out.TotalCount-1)/size
		page := pagination.Page[*DescribeVpcsOutput]{Value: out, HasMore: more}
		if more {
			page.Next = pagination.Cursor{PageNumber: cursor.PageNumber + 1}
		}
		return page, nil
	})
	if err != nil {
		return nil, err
	}
	return &DescribeVpcsPaginator{engine: engine}, nil
}

// HasMorePages reports whether another service page is available.
func (p *DescribeVpcsPaginator) HasMorePages() bool { return p.engine.HasMorePages() }

// NextPage fetches without modifying input; errors preserve the current cursor.
func (p *DescribeVpcsPaginator) NextPage(ctx context.Context) (*DescribeVpcsOutput, error) {
	return p.engine.NextPage(ctx)
}
