// Code generated by sdkgen; DO NOT EDIT.

// Package vpc provides generated DescribeVpcs and a page-number paginator for Vpc API 2016-04-28. Coverage includes selected fields only. Use New with shared Config; clients are concurrency safe and inputs are copied. Errors preserve structured service causes and context cancellation.
package vpc
