// Code generated by sdkgen; DO NOT EDIT.
package vpc

import (
	"context"
	"encoding/json/v2"
	"errors"
	alicloud "github.com/rambow-cloud/alicloud-go-sdk-x"
	"net/url"
	"strconv"
)

// Options aliases shared per-call runtime options.
type Options = alicloud.CallOptions

// Client is a concurrency-safe Vpc client. Construct it with New.
type Client struct{ runtime *alicloud.Client }

// New validates and copies runtime configuration. Custom extension objects must be concurrency safe.
func New(config alicloud.Config) (*Client, error) {
	c, err := alicloud.NewClient(config)
	if err != nil {
		return nil, err
	}
	return &Client{runtime: c}, nil
}

// IPv6Block contains a selected IPv6 block and its ISP.
type IPv6Block struct {
	// ISP contains selected wire field Ipv6Isp.
	ISP string `json:"Ipv6Isp"`
	// CIDRBlock contains selected wire field Ipv6CidrBlock.
	CIDRBlock string `json:"Ipv6CidrBlock"`
}

// Tag contains a returned VPC tag.
type Tag struct {
	// Key contains selected wire field Key.
	Key string `json:"Key"`
	// Value contains selected wire field Value.
	Value string `json:"Value"`
}

// TagFilter selects one reviewed tag filter; pointer members are copied before use.
type TagFilter struct {
	// Key selects a nonempty tag key of up to 128 Unicode characters; reserved prefixes and URL substrings are rejected.
	Key string `json:"Key"`
	// Value selects an optional tag value of up to 128 Unicode characters; nil omits it and new("") explicitly sends an empty value.
	// Nil omits the field; a non-nil pointer preserves an explicit zero value.
	Value *string `json:"Value"`
}

func cloneTagFilter(in TagFilter) TagFilter {
	out := in
	if in.Value != nil {
		copied := *in.Value
		out.Value = &copied
	}
	return out
}

// VPC contains selected VPC properties with flattened nested containers; unknown response fields are ignored.
type VPC struct {
	// VPCID contains selected wire field VpcId.
	VPCID string `json:"VpcId"`
	// Name contains selected wire field VpcName.
	Name string `json:"VpcName"`
	// RegionID contains selected wire field RegionId.
	RegionID string `json:"RegionId"`
	// Status contains the service lifecycle state; unknown future values are retained.
	Status string `json:"Status"`
	// CIDRBlock contains selected wire field CidrBlock.
	CIDRBlock string `json:"CidrBlock"`
	// IPv6CIDRBlock contains selected wire field Ipv6CidrBlock.
	IPv6CIDRBlock string `json:"Ipv6CidrBlock"`
	// IsDefault contains selected wire field IsDefault.
	IsDefault bool `json:"IsDefault"`
	// IPv6Enabled contains selected wire field EnabledIpv6.
	IPv6Enabled bool `json:"EnabledIpv6"`
	// OwnerID contains the owner account ID without floating-point conversion.
	OwnerID int64 `json:"OwnerId"`
	// Tags contains selected wire field Tags.Tag.
	Tags []Tag `json:"Tags.Tag"`
	// IPv6Blocks contains selected wire field Ipv6CidrBlocks.Ipv6CidrBlock.
	IPv6Blocks []IPv6Block `json:"Ipv6CidrBlocks.Ipv6CidrBlock"`
	// VSwitchIDs contains the service-returned vSwitch ID subset; use the dedicated API for a complete list.
	VSwitchIDs []string `json:"VSwitchIds.VSwitchId"`
}

// UnmarshalJSON decodes selected wire fields with JSON v2; errors leave the receiver unchanged.
func (out *VPC) UnmarshalJSON(data []byte) error {
	var wire struct {
		W0 string `json:"CidrBlock"`
		W1 bool   `json:"EnabledIpv6"`
		W2 string `json:"Ipv6CidrBlock"`
		W3 struct {
			W0 []IPv6Block `json:"Ipv6CidrBlock"`
		} `json:"Ipv6CidrBlocks"`
		W4 bool   `json:"IsDefault"`
		W5 int64  `json:"OwnerId"`
		W6 string `json:"RegionId"`
		W7 string `json:"Status"`
		W8 struct {
			W0 []Tag `json:"Tag"`
		} `json:"Tags"`
		W9 struct {
			W0 []string `json:"VSwitchId"`
		} `json:"VSwitchIds"`
		W10 string `json:"VpcId"`
		W11 string `json:"VpcName"`
	}
	if err := json.Unmarshal(data, &wire); err != nil {
		return err
	}
	*out = VPC{VPCID: wire.W10, Name: wire.W11, RegionID: wire.W6, Status: wire.W7, CIDRBlock: wire.W0, IPv6CIDRBlock: wire.W2, IsDefault: wire.W4, IPv6Enabled: wire.W1, OwnerID: wire.W5, Tags: wire.W8.W0, IPv6Blocks: wire.W3.W0, VSwitchIDs: wire.W9.W0}
	return nil
}

// MarshalJSON restores reviewed wire containers with JSON v2.
func (in VPC) MarshalJSON() ([]byte, error) {
	var wire struct {
		W0 string `json:"CidrBlock"`
		W1 bool   `json:"EnabledIpv6"`
		W2 string `json:"Ipv6CidrBlock"`
		W3 struct {
			W0 []IPv6Block `json:"Ipv6CidrBlock"`
		} `json:"Ipv6CidrBlocks"`
		W4 bool   `json:"IsDefault"`
		W5 int64  `json:"OwnerId"`
		W6 string `json:"RegionId"`
		W7 string `json:"Status"`
		W8 struct {
			W0 []Tag `json:"Tag"`
		} `json:"Tags"`
		W9 struct {
			W0 []string `json:"VSwitchId"`
		} `json:"VSwitchIds"`
		W10 string `json:"VpcId"`
		W11 string `json:"VpcName"`
	}
	wire.W10 = in.VPCID
	wire.W11 = in.Name
	wire.W6 = in.RegionID
	wire.W7 = in.Status
	wire.W0 = in.CIDRBlock
	wire.W2 = in.IPv6CIDRBlock
	wire.W4 = in.IsDefault
	wire.W1 = in.IPv6Enabled
	wire.W5 = in.OwnerID
	wire.W8.W0 = in.Tags
	wire.W3.W0 = in.IPv6Blocks
	wire.W9.W0 = in.VSwitchIDs
	return json.Marshal(wire)
}

// DescribeVpcsInput contains the selected query parameters; zero optional values are omitted.
type DescribeVpcsInput struct {
	// RegionID defaults to the client region; the per-call region override takes precedence.
	RegionID string
	// VPCID selects a VPC ID or up to twenty comma-separated IDs; empty omits the filter.
	VPCID string
	// Name selects a VPC name; empty omits the filter.
	Name string
	// ResourceGroupID selects a resource group; empty omits the filter.
	ResourceGroupID string
	// DhcpOptionsSetID selects a DHCP options set; empty omits the filter.
	DhcpOptionsSetID string
	// IsDefault selects the default-VPC filter; nil delegates omission/default behavior to the service.
	// Nil omits the field; a non-nil pointer preserves an explicit zero value.
	IsDefault *bool
	// DryRun requests a preflight when true; DryRunOperation remains a structured service error.
	// Nil omits the field; a non-nil pointer preserves an explicit zero value.
	DryRun *bool
	// IPv6Enabled filters IPv6 enablement; nil means no filter, false selects disabled and true selects enabled.
	// Nil omits the field; a non-nil pointer preserves an explicit zero value.
	IPv6Enabled *bool
	// OwnerID selects an owner account; zero omits the filter and negative values are rejected.
	OwnerID int64
	// PageNumber selects a one-based page; zero omits it (service default one).
	// Nonzero values must be at least 1.
	PageNumber int
	// PageSize selects up to fifty results per page; zero omits it (service default ten).
	// Nonzero values must be at least 1.
	// Nonzero values must be at most 50.
	PageSize int
	// Tags selects up to twenty tag filters encoded as Tag.N.Key/Value; all pointer and slice members are copied.
	Tags []TagFilter
}

// DescribeVpcsOutput contains selected response fields and transport metadata.
type DescribeVpcsOutput struct {
	// VPCs contains selected wire field Vpcs.Vpc.
	VPCs []VPC
	// PageNumber contains selected wire field PageNumber.
	PageNumber int `json:"PageNumber"`
	// PageSize contains selected wire field PageSize.
	PageSize int `json:"PageSize"`
	// TotalCount contains the matching count used by page-number traversal.
	TotalCount int `json:"TotalCount"`
	// Metadata contains request ID, status and attempt count; it is excluded from wire decoding.
	Metadata alicloud.Metadata `json:"-"`
}

// DescribeVpcsAPI is the minimal operation interface for consumers and fakes.
type DescribeVpcsAPI interface {
	// DescribeVpcs queries one selected VPC page; nil input uses the client region and service defaults. Callers must not mutate input concurrently.
	DescribeVpcs(context.Context, *DescribeVpcsInput, ...func(*Options)) (*DescribeVpcsOutput, error)
}

// DescribeVpcs queries one selected VPC page; nil input uses the client region and service defaults. Callers must not mutate input concurrently.
// API version 2016-04-28. Errors preserve cancellation and structured service causes.
func (c *Client) DescribeVpcs(ctx context.Context, input *DescribeVpcsInput, opts ...func(*Options)) (*DescribeVpcsOutput, error) {
	fail := func(err error) (*DescribeVpcsOutput, error) {
		return nil, generatedValidation(ctx, "DescribeVpcs", err)
	}
	if err := ctx.Err(); err != nil {
		return fail(err)
	}
	var in DescribeVpcsInput
	if input != nil {
		in = *input
		if input.IsDefault != nil {
			copied := *input.IsDefault
			in.IsDefault = &copied
		}
		if input.DryRun != nil {
			copied := *input.DryRun
			in.DryRun = &copied
		}
		if input.IPv6Enabled != nil {
			copied := *input.IPv6Enabled
			in.IPv6Enabled = &copied
		}
		in.Tags = append([]TagFilter(nil), input.Tags...)
		for i := range in.Tags {
			in.Tags[i] = cloneTagFilter(in.Tags[i])
		}
	}
	if err := validateDescribeVpcs(in); err != nil {
		return fail(err)
	}
	region := ""
	q := url.Values{}
	region = in.RegionID
	if region == "" {
		region = c.runtime.Region()
	}
	q.Set("RegionId", region)
	if in.VPCID != "" {
		q.Set("VpcId", in.VPCID)
	}
	if in.Name != "" {
		q.Set("VpcName", in.Name)
	}
	if in.ResourceGroupID != "" {
		q.Set("ResourceGroupId", in.ResourceGroupID)
	}
	if in.DhcpOptionsSetID != "" {
		q.Set("DhcpOptionsSetId", in.DhcpOptionsSetID)
	}
	if in.IsDefault != nil {
		q.Set("IsDefault", strconv.FormatBool(*in.IsDefault))
	}
	if in.DryRun != nil {
		q.Set("DryRun", strconv.FormatBool(*in.DryRun))
	}
	if in.IPv6Enabled != nil {
		q.Set("EnableIpv6", strconv.FormatBool(*in.IPv6Enabled))
	}
	if in.OwnerID != 0 {
		q.Set("VpcOwnerId", strconv.FormatInt(in.OwnerID, 10))
	}
	if in.PageNumber != 0 && in.PageNumber < 1 {
		return fail(errors.New("parameter below minimum: PageNumber"))
	}
	if in.PageNumber != 0 {
		q.Set("PageNumber", strconv.Itoa(in.PageNumber))
	}
	if in.PageSize != 0 && in.PageSize < 1 {
		return fail(errors.New("parameter below minimum: PageSize"))
	}
	if in.PageSize != 0 && in.PageSize > 50 {
		return fail(errors.New("parameter above maximum: PageSize"))
	}
	if in.PageSize != 0 {
		q.Set("PageSize", strconv.Itoa(in.PageSize))
	}
	if len(in.Tags) > 20 {
		return fail(errors.New("array too large: Tag"))
	}
	for i, item := range in.Tags {
		prefix := "Tag." + strconv.Itoa(i+1) + "."
		if item.Key != "" {
			q.Set(prefix+"Key", item.Key)
		}
		if item.Value != nil {
			q.Set(prefix+"Value", *item.Value)
		}
	}
	var wire struct {
		W0 int `json:"PageNumber"`
		W1 int `json:"PageSize"`
		W2 int `json:"TotalCount"`
		W3 struct {
			W0 []VPC `json:"Vpc"`
		} `json:"Vpcs"`
	}
	meta, err := c.runtime.Invoke(ctx, alicloud.Operation{Service: "vpc", Name: "DescribeVpcs", Version: "2016-04-28", Idempotent: true}, alicloud.Request{Method: "POST", Path: "/", Region: region, Query: q, Header: map[string][]string{"Content-Type": {"application/x-www-form-urlencoded"}}}, &wire, opts...)
	if err != nil {
		return nil, err
	}
	return &DescribeVpcsOutput{Metadata: meta, VPCs: wire.W3.W0, PageNumber: wire.W0, PageSize: wire.W1, TotalCount: wire.W2}, nil
}
func generatedValidation(ctx context.Context, name string, err error) error {
	if ctx.Err() != nil {
		err = ctx.Err()
	}
	return &alicloud.OperationError{Service: "vpc", Operation: name, Err: err}
}
